// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum WelcomeL10n {
    public enum Main {
        /// Access Granted
        public static var accessGranted: String { WelcomeL10n.string("welcome.main.accessGranted") }
        /// Alike
        public static var alike: String { WelcomeL10n.string("welcome.main.alike") }
        /// Alike data deleted
        public static var alikeDataDeleted: String { WelcomeL10n.string("welcome.main.alikeDataDeleted") }
        /// Alike needs photo access to scan your library and prepare cleanup suggestions.
        public static var alikeNeedsPhotoAccessScan: String { WelcomeL10n.string("welcome.main.alikeNeedsPhotoAccessScan") }
        /// Alike never deletes photos automatically. You review the suggestions first and confirm every clea...
        public static var alikeNeverDeletesPhotosAutomatically: String { WelcomeL10n.string("welcome.main.alikeNeverDeletesPhotosAutomatically") }
        /// Alike, your photo detective
        public static var alikeYourPhotoDetective: String { WelcomeL10n.string("welcome.main.alikeYourPhotoDetective") }
        /// Analysis stays on your device, and nothing is deleted automatically.
        public static var analysisStaysDeviceNothingDeleted: String { WelcomeL10n.string("welcome.main.analysisStaysDeviceNothingDeleted") }
        /// Back
        public static var back: String { WelcomeL10n.string("welcome.main.back") }
        /// You can change access later in Settings, and Alike never deletes anything without your confirmation.
        public static var canChangeAccessLaterSettings: String { WelcomeL10n.string("welcome.main.canChangeAccessLaterSettings") }
        /// You can grant access now and return to cleanup whenever you're ready.
        public static var canGrantAccessNowReturn: String { WelcomeL10n.string("welcome.main.canGrantAccessNowReturn") }
        /// Clean up your library with confidence
        public static var cleanUpLibraryWithConfidence: String { WelcomeL10n.string("welcome.main.cleanUpLibraryWithConfidence") }
        /// Compare photos and keep the shots that matter to you.
        public static var comparePhotosKeepShotsThat: String { WelcomeL10n.string("welcome.main.comparePhotosKeepShotsThat") }
        /// Continue
        public static var `continue`: String { WelcomeL10n.string("welcome.main.continue") }
        /// Enable photo access in Settings when you're ready to continue.
        public static var enablePhotoAccessSettingsWhen: String { WelcomeL10n.string("welcome.main.enablePhotoAccessSettingsWhen") }
        /// Every deletion stays confirmed, visible, and fully in your hands.
        public static var everyDeletionStaysConfirmedVisible: String { WelcomeL10n.string("welcome.main.everyDeletionStaysConfirmedVisible") }
        /// Find cleanup opportunities
        public static var findCleanupOpportunities: String { WelcomeL10n.string("welcome.main.findCleanupOpportunities") }
        /// Grant Access
        public static var grantAccess: String { WelcomeL10n.string("welcome.main.grantAccess") }
        /// Group visually similar photos and other items worth reviewing.
        public static var groupVisuallySimilarPhotosOther: String { WelcomeL10n.string("welcome.main.groupVisuallySimilarPhotosOther") }
        /// How Alike helps
        public static var howAlikeHelps: String { WelcomeL10n.string("welcome.main.howAlikeHelps") }
        /// Know how much space you could reclaim before you clean up.
        public static var knowHowMuchSpaceCould: String { WelcomeL10n.string("welcome.main.knowHowMuchSpaceCould") }
        /// Your local Alike data was deleted. Your photos and subscription are unchanged.
        public static var localAlikeDataWasDeleted: String { WelcomeL10n.string("welcome.main.localAlikeDataWasDeleted") }
        /// Next
        public static var next: String { WelcomeL10n.string("welcome.main.next") }
        /// Nothing is deleted automatically
        public static var nothingIsDeletedAutomatically: String { WelcomeL10n.string("welcome.main.nothingIsDeletedAutomatically") }
        /// Open Settings
        public static var openSettings: String { WelcomeL10n.string("welcome.main.openSettings") }
        /// Page %lld of %lld
        public static var pageOf: String { WelcomeL10n.string("welcome.main.pageOf") }
        /// Photo access lets Alike scan your library, group similar photos, and prepare cleanup suggestions ...
        public static var photoAccessLetsAlikeScan: String { WelcomeL10n.string("welcome.main.photoAccessLetsAlikeScan") }
        /// Photo Access Required
        public static var photoAccessRequired: String { WelcomeL10n.string("welcome.main.photoAccessRequired") }
        /// Your photo analysis stays on this device and gives you guided cleanup suggestions.
        public static var photoAnalysisStaysThisDevice: String { WelcomeL10n.string("welcome.main.photoAnalysisStaysThisDevice") }
        /// Your photos stay private, and you'll confirm every cleanup before anything is removed.
        public static var photosStayPrivateYoullConfirm: String { WelcomeL10n.string("welcome.main.photosStayPrivateYoullConfirm") }
        /// Private and always in your control
        public static var privateAlwaysControl: String { WelcomeL10n.string("welcome.main.privateAlwaysControl") }
        /// Private on-device analysis
        public static var privateOnDeviceAnalysis: String { WelcomeL10n.string("welcome.main.privateOnDeviceAnalysis") }
        /// Review every suggestion
        public static var reviewEverySuggestion: String { WelcomeL10n.string("welcome.main.reviewEverySuggestion") }
        /// Review similar photos, free up storage, and stay in control of every deletion.
        public static var reviewSimilarPhotosFreeUp: String { WelcomeL10n.string("welcome.main.reviewSimilarPhotosFreeUp") }
        /// You review suggestions first and confirm every cleanup action yourself.
        public static var reviewSuggestionsFirstConfirmEvery: String { WelcomeL10n.string("welcome.main.reviewSuggestionsFirstConfirmEvery") }
        /// Safe cleanup flow
        public static var safeCleanupFlow: String { WelcomeL10n.string("welcome.main.safeCleanupFlow") }
        /// See potential savings
        public static var seePotentialSavings: String { WelcomeL10n.string("welcome.main.seePotentialSavings") }
        /// Spot similar photos that can free up space once you decide what to remove.
        public static var spotSimilarPhotosThatCan: String { WelcomeL10n.string("welcome.main.spotSimilarPhotosThatCan") }
        /// Storage savings
        public static var storageSavings: String { WelcomeL10n.string("welcome.main.storageSavings") }
        /// Turn a crowded library into a guided cleanup.
        public static var turnCrowdedLibraryIntoGuided: String { WelcomeL10n.string("welcome.main.turnCrowdedLibraryIntoGuided") }
        /// Why Alike asks for photo access
        public static var whyAlikeAsksPhotoAccess: String { WelcomeL10n.string("welcome.main.whyAlikeAsksPhotoAccess") }
        /// Your library stays under your control
        public static var yourLibraryStaysUnderControl: String { WelcomeL10n.string("welcome.main.yourLibraryStaysUnderControl") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }
}
