// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum SettingsL10n {
    public enum DeleteAllDataModel {
        /// Some data may already have been removed. Please try again to finish deleting your Alike data.
        public static var someDataMayAlreadyHave: String { SettingsL10n.string("settings.deleteAllDataModel.someDataMayAlreadyHave") }
    }

    public enum Main {
        /// Your cleanup reminder couldn't be updated. Please try again.
        public static var cleanupReminderCouldntBeUpdated: String { SettingsL10n.string("settings.main.cleanupReminderCouldntBeUpdated") }
        /// Alike Pro is active
        public static var alikeProIsActive: String { SettingsL10n.string("settings.main.alikeProIsActive") }
        /// Your Alike Pro subscription was restored.
        public static var alikeProSubscriptionWasRestored: String { SettingsL10n.string("settings.main.alikeProSubscriptionWasRestored") }
        /// Analysis
        public static var analysis: String { SettingsL10n.string("settings.main.analysis") }
        /// You can continue using Alike Free.
        public static var canContinueUsingAlikeFree: String { SettingsL10n.string("settings.main.canContinueUsingAlikeFree") }
        /// Cancel
        public static var cancel: String { SettingsL10n.string("settings.main.cancel") }
        /// Change Language
        public static var changeLanguage: String { SettingsL10n.string("settings.main.changeLanguage") }
        /// Cleanup progress, sessions, and history
        public static var cleanupProgressSessionsAndHistory: String { SettingsL10n.string("settings.main.cleanupProgressSessionsAndHistory") }
        /// Cleanup Reminder
        public static var cleanupReminder: String { SettingsL10n.string("settings.main.cleanupReminder") }
        /// Contact Developer
        public static var contactDeveloper: String { SettingsL10n.string("settings.main.contactDeveloper") }
        /// Couldn't Delete Alike Data
        public static var couldntDeleteAlikeData: String { SettingsL10n.string("settings.main.couldntDeleteAlikeData") }
        /// Couldn't Restore Purchases
        public static var couldntRestorePurchases: String { SettingsL10n.string("settings.main.couldntRestorePurchases") }
        /// Couldn't Update Reminder
        public static var couldntUpdateReminder: String { SettingsL10n.string("settings.main.couldntUpdateReminder") }
        /// Customize day & time
        public static var customizeDayTime: String { SettingsL10n.string("settings.main.customizeDayTime") }
        /// Data & Privacy
        public static var dataPrivacy: String { SettingsL10n.string("settings.main.dataPrivacy") }
        /// Debug
        public static var debug: String { SettingsL10n.string("settings.main.debug") }
        /// Delete Alike Data
        public static var deleteAlikeData: String { SettingsL10n.string("settings.main.deleteAlikeData") }
        /// Delete all Alike data?
        public static var deleteAllAlikeData: String { SettingsL10n.string("settings.main.deleteAllAlikeData") }
        /// Deleting...
        public static var deleting: String { SettingsL10n.string("settings.main.deleting") }
        /// Enable premium blurred photo cleanup access in debug builds
        public static var enablePremiumBlurredPhotoCleanup: String { SettingsL10n.string("settings.main.enablePremiumBlurredPhotoCleanup") }
        /// Enable premium reminder schedule customization in debug builds
        public static var enablePremiumReminderScheduleCustomization: String { SettingsL10n.string("settings.main.enablePremiumReminderScheduleCustomization") }
        /// Enable premium screenshot cleanup access in debug builds
        public static var enablePremiumScreenshotCleanupAccess: String { SettingsL10n.string("settings.main.enablePremiumScreenshotCleanupAccess") }
        /// Enable a weekly reminder to come back and continue cleanup
        public static var enableWeeklyReminderComeBack: String { SettingsL10n.string("settings.main.enableWeeklyReminderComeBack") }
        /// Free reminders use Sunday at 6:00 PM. Unlock premium to choose your own day and time.
        public static var freeRemindersUseSundayAt: String { SettingsL10n.string("settings.main.freeRemindersUseSundayAt") }
        /// Free reminders use Sunday at 6:00 PM. — locale/bundle-injectable, see above.
        public static func freeRemindersUseSundayAt(bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            SettingsL10n.string("settings.main.freeRemindersUseSundayAt", bundle: bundle, locale: locale)
        }
        /// Grid, sensitivity, and reminder preferences
        public static var gridSensitivityAndReminderPreferences: String { SettingsL10n.string("settings.main.gridSensitivityAndReminderPreferences") }
        /// Higher sensitivity finds more similar photos but may include less alike images
        public static var higherSensitivityFindsMoreSimilar: String { SettingsL10n.string("settings.main.higherSensitivityFindsMoreSimilar") }
        /// How to Use
        public static var howToUse: String { SettingsL10n.string("settings.main.howToUse") }
        /// Language
        public static var language: String { SettingsL10n.string("settings.main.language") }
        /// Legal
        public static var legal: String { SettingsL10n.string("settings.main.legal") }
        /// Monthly free-scan allowance
        public static var monthlyFreeScanAllowance: String { SettingsL10n.string("settings.main.monthlyFreeScanAllowance") }
        /// No active Alike Pro subscription was found.
        public static var noActiveAlikeProSubscription: String { SettingsL10n.string("settings.main.noActiveAlikeProSubscription") }
        /// Notifications are turned off for Alike. Enable them in Settings to receive your weekly cleanup re...
        public static var notificationsTurnedOffAlikeEnable: String { SettingsL10n.string("settings.main.notificationsTurnedOffAlikeEnable") }
        /// OK
        public static var ok: String { SettingsL10n.string("settings.main.ok") }
        /// Open the Alike privacy policy in your browser
        public static var openAlikePrivacyPolicyBrowser: String { SettingsL10n.string("settings.main.openAlikePrivacyPolicyBrowser") }
        /// Open the Alike terms of use in your browser
        public static var openAlikeTermsUseBrowser: String { SettingsL10n.string("settings.main.openAlikeTermsUseBrowser") }
        /// Open email composer to contact the developer
        public static var openEmailComposerContactDeveloper: String { SettingsL10n.string("settings.main.openEmailComposerContactDeveloper") }
        /// Open premium details for custom cleanup reminder scheduling
        public static var openPremiumDetailsCustomCleanup: String { SettingsL10n.string("settings.main.openPremiumDetailsCustomCleanup") }
        /// Open Settings
        public static var openSettings: String { SettingsL10n.string("settings.main.openSettings") }
        /// Open system settings to change app language
        public static var openSystemSettingsChangeApp: String { SettingsL10n.string("settings.main.openSystemSettingsChangeApp") }
        /// Open usage instructions and cleanup workflow tips
        public static var openUsageInstructionsCleanupWorkflow: String { SettingsL10n.string("settings.main.openUsageInstructionsCleanupWorkflow") }
        /// Permanently delete Alike data after confirmation
        public static var permanentlyDeleteAlikeDataAfter: String { SettingsL10n.string("settings.main.permanentlyDeleteAlikeDataAfter") }
        /// Photo access and Alike Pro subscription
        public static var photoAccessAlikeProSubscription: String { SettingsL10n.string("settings.main.photoAccessAlikeProSubscription") }
        /// Your photo library is never deleted by this action.
        public static var photoLibraryNeverDeletedBy: String { SettingsL10n.string("settings.main.photoLibraryNeverDeletedBy") }
        /// Your photos and Recently Deleted items
        public static var photosRecentlyDeletedItems: String { SettingsL10n.string("settings.main.photosRecentlyDeletedItems") }
        /// Please check your connection and try restoring again.
        public static var pleaseCheckConnectionTryRestoring: String { SettingsL10n.string("settings.main.pleaseCheckConnectionTryRestoring") }
        /// Premium lets you choose a custom weekly reminder schedule.
        public static var premiumLetsChooseCustomWeekly: String { SettingsL10n.string("settings.main.premiumLetsChooseCustomWeekly") }
        /// Privacy Policy
        public static var privacyPolicy: String { SettingsL10n.string("settings.main.privacyPolicy") }
        /// Rate on App Store
        public static var rateOnAppStore: String { SettingsL10n.string("settings.main.rateOnAppStore") }
        /// Reminder day
        public static var reminderDay: String { SettingsL10n.string("settings.main.reminderDay") }
        /// Reminder schedule
        public static var reminderSchedule: String { SettingsL10n.string("settings.main.reminderSchedule") }
        /// %1$@ at %2$@
        public static var reminderScheduleWeekdayTime: String { SettingsL10n.string("settings.main.reminderScheduleWeekdayTime") }
        /// %1$@ at %2$@ — locale/bundle-injectable so tests can pin the formatted schedule.
        public static func reminderScheduleWeekdayTime(bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            SettingsL10n.string("settings.main.reminderScheduleWeekdayTime", bundle: bundle, locale: locale)
        }
        /// Reminder time
        public static var reminderTime: String { SettingsL10n.string("settings.main.reminderTime") }
        /// Request the App Store rating prompt
        public static var requestAppStoreRatingPrompt: String { SettingsL10n.string("settings.main.requestAppStoreRatingPrompt") }
        /// Review and permanently delete data stored by Alike on this device
        public static var reviewPermanentlyDeleteDataStored: String { SettingsL10n.string("settings.main.reviewPermanentlyDeleteDataStored") }
        /// Scan results and analysis caches
        public static var scanResultsAndAnalysisCaches: String { SettingsL10n.string("settings.main.scanResultsAndAnalysisCaches") }
        /// Sensitivity
        public static var sensitivity: String { SettingsL10n.string("settings.main.sensitivity") }
        /// Settings
        public static var settings: String { SettingsL10n.string("settings.main.settings") }
        /// Share App
        public static var shareApp: String { SettingsL10n.string("settings.main.shareApp") }
        /// Share the app using available sharing options
        public static var shareAppUsingAvailableSharing: String { SettingsL10n.string("settings.main.shareAppUsingAvailableSharing") }
        /// Subscription
        public static var subscription: String { SettingsL10n.string("settings.main.subscription") }
        /// Support
        public static var support: String { SettingsL10n.string("settings.main.support") }
        /// Terms of Use
        public static var termsOfUse: String { SettingsL10n.string("settings.main.termsOfUse") }
        /// This action can't be undone. Alike will replay onboarding when deletion finishes.
        public static var thisActionCantBeUndone: String { SettingsL10n.string("settings.main.thisActionCantBeUndone") }
        /// This override is available only in debug builds and affects local premium gating.
        public static var thisOverrideAvailableOnlyDebug: String { SettingsL10n.string("settings.main.thisOverrideAvailableOnlyDebug") }
        /// This permanently deletes Alike's local results, cleanup history, and preferences. Your photos and...
        public static var thisPermanentlyDeletesAlikesLocal: String { SettingsL10n.string("settings.main.thisPermanentlyDeletesAlikesLocal") }
        /// Try Again
        public static var tryAgain: String { SettingsL10n.string("settings.main.tryAgain") }
        /// Unlock Advanced Filters Premium Feature
        public static var unlockAdvancedFiltersPremiumFeature: String { SettingsL10n.string("settings.main.unlockAdvancedFiltersPremiumFeature") }
        /// Unlock Batch Cleanup Premium Feature
        public static var unlockBatchCleanupPremiumFeature: String { SettingsL10n.string("settings.main.unlockBatchCleanupPremiumFeature") }
        /// Unlock Blurred Photo Cleanup Premium Feature
        public static var unlockBlurredPhotoCleanupPremium: String { SettingsL10n.string("settings.main.unlockBlurredPhotoCleanupPremium") }
        /// Unlock Custom Reminder Schedule Premium Feature
        public static var unlockCustomReminderSchedulePremium: String { SettingsL10n.string("settings.main.unlockCustomReminderSchedulePremium") }
        /// Unlock Screenshot Cleanup Premium Feature
        public static var unlockScreenshotCleanupPremiumFeature: String { SettingsL10n.string("settings.main.unlockScreenshotCleanupPremiumFeature") }
        /// Unlock Unlimited Scans Premium Feature
        public static var unlockUnlimitedScansPremiumFeature: String { SettingsL10n.string("settings.main.unlockUnlimitedScansPremiumFeature") }
        /// Version
        public static var version: String { SettingsL10n.string("settings.main.version") }
        /// Weekly cleanup reminder
        public static var weeklyCleanupReminder: String { SettingsL10n.string("settings.main.weeklyCleanupReminder") }
        /// What will be deleted
        public static var whatWillBeDeleted: String { SettingsL10n.string("settings.main.whatWillBeDeleted") }
        /// What will stay
        public static var whatWillStay: String { SettingsL10n.string("settings.main.whatWillStay") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }

    /// Same lookup, but with the bundle/locale exposed so tests can resolve against a compiled
    /// fixture and a fixed locale instead of the live device state.
    static func string(_ key: String.LocalizationValue, bundle: Bundle?, locale: Locale?) -> String {
        String(localized: key, bundle: bundle ?? .module, locale: locale ?? .current)
    }
}
