// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum PurchasesL10n {
    public enum Common {
        /// Alike Pro
        public static var alikePro: String { PurchasesL10n.string("purchases.common.alikePro") }
        /// Alike Pro is active
        public static var alikeProIsActive: String { PurchasesL10n.string("purchases.common.alikeProIsActive") }
        /// Clean up all selected photos with Pro
        public static var cleanUpAllSelectedPhotos: String { PurchasesL10n.string("purchases.common.cleanUpAllSelectedPhotos") }
        /// Restore Purchases
        public static var restorePurchases: String { PurchasesL10n.string("purchases.common.restorePurchases") }
    }

    public enum Premium {
        /// Choose the weekly reminder day and time that fits your routine.
        public static var chooseWeeklyReminderDayTime: String { PurchasesL10n.string("purchases.premium.chooseWeeklyReminderDayTime") }
        /// Find the photos that matter faster
        public static var findPhotosThatMatterFaster: String { PurchasesL10n.string("purchases.premium.findPhotosThatMatterFaster") }
        /// You found your first cleanup opportunities
        public static var foundFirstCleanupOpportunities: String { PurchasesL10n.string("purchases.premium.foundFirstCleanupOpportunities") }
        /// Free includes %1$d scans per calendar month. You have %2$d remaining and the allowance resets %3$@.
        public static var freeIncludesScansPerCalendar: String { PurchasesL10n.string("purchases.premium.freeIncludesScansPerCalendar") }
        /// Free includes %1$d scans per calendar month. You have %2$d remaining.
        public static var freeIncludesScansPerCalendar2: String { PurchasesL10n.string("purchases.premium.freeIncludesScansPerCalendar2") }
        /// Free includes three scans per calendar month. Pro keeps your cleanup results current whenever you...
        public static var freeIncludesThreeScansPer: String { PurchasesL10n.string("purchases.premium.freeIncludesThreeScansPer") }
        /// Keep scanning without monthly limits
        public static var keepScanningWithoutMonthlyLimits: String { PurchasesL10n.string("purchases.premium.keepScanningWithoutMonthlyLimits") }
        /// Make cleanup fit your schedule
        public static var makeCleanupFitYourSchedule: String { PurchasesL10n.string("purchases.premium.makeCleanupFitYourSchedule") }
        /// Make every cleanup faster with Alike Pro
        public static var makeEveryCleanupFasterWith: String { PurchasesL10n.string("purchases.premium.makeEveryCleanupFasterWith") }
        /// Remove multiple selected photos in one safe, confirmed action.
        public static var removeMultipleSelectedPhotosOne: String { PurchasesL10n.string("purchases.premium.removeMultipleSelectedPhotosOne") }
        /// Review likely blurred photos faster
        public static var reviewLikelyBlurredPhotosFaster: String { PurchasesL10n.string("purchases.premium.reviewLikelyBlurredPhotosFaster") }
        /// Review likely low-quality shots before deciding what to keep or remove.
        public static var reviewLikelyLowQualityShots: String { PurchasesL10n.string("purchases.premium.reviewLikelyLowQualityShots") }
        /// Review screenshots together and choose exactly what should move to Recently Deleted.
        public static var reviewScreenshotsTogetherChooseExactly: String { PurchasesL10n.string("purchases.premium.reviewScreenshotsTogetherChooseExactly") }
        /// Review smart cleanup suggestions while keeping full control over every deletion.
        public static var reviewSmartCleanupSuggestionsWhile: String { PurchasesL10n.string("purchases.premium.reviewSmartCleanupSuggestionsWhile") }
        /// Review this smart category and reclaim an estimated %@.
        public static var reviewThisSmartCategoryReclaim: String { PurchasesL10n.string("purchases.premium.reviewThisSmartCategoryReclaim") }
        /// Turn screenshot clutter into free space
        public static var turnScreenshotClutterIntoFree: String { PurchasesL10n.string("purchases.premium.turnScreenshotClutterIntoFree") }
        /// Unlock review status, cluster size, and favorites filters for faster cleanup.
        public static var unlockReviewStatusClusterSize: String { PurchasesL10n.string("purchases.premium.unlockReviewStatusClusterSize") }
        /// Unlock unlimited scans, smart categories, advanced filters, batch cleanup, and custom reminders.
        public static var unlockUnlimitedScansSmartCategories: String { PurchasesL10n.string("purchases.premium.unlockUnlimitedScansSmartCategories") }
        /// Unlock %@ with Alike Pro
        public static var unlockWithAlikePro: String { PurchasesL10n.string("purchases.premium.unlockWithAlikePro") }
    }

    public enum PremiumComponents {
        /// %1$@ • Active through %2$@
        public static var activeThrough: String { PurchasesL10n.string("purchases.premiumComponents.activeThrough") }
        /// Alike Pro status unavailable
        public static var alikeProStatusUnavailable: String { PurchasesL10n.string("purchases.premiumComponents.alikeProStatusUnavailable") }
        /// Checking Alike Pro
        public static var checkingAlikePro: String { PurchasesL10n.string("purchases.premiumComponents.checkingAlikePro") }
        /// Checking subscription status
        public static var checkingSubscriptionStatus: String { PurchasesL10n.string("purchases.premiumComponents.checkingSubscriptionStatus") }
        /// Confirming your App Store subscription status.
        public static var confirmingAppStoreSubscriptionStatus: String { PurchasesL10n.string("purchases.premiumComponents.confirmingAppStoreSubscriptionStatus") }
        /// Continue with one photo
        public static var continueWithOnePhoto: String { PurchasesL10n.string("purchases.premiumComponents.continueWithOnePhoto") }
        /// Your current access is preserved. Open plans to retry loading subscription details.
        public static var currentAccessPreservedOpenPlans: String { PurchasesL10n.string("purchases.premiumComponents.currentAccessPreservedOpenPlans") }
        /// Pro
        public static var pro: String { PurchasesL10n.string("purchases.premiumComponents.pro") }
        /// Requires Alike Pro
        public static var requiresAlikePro: String { PurchasesL10n.string("purchases.premiumComponents.requiresAlikePro") }
        /// %1$d selected • %2$@ estimated reclaimable
        public static var selectedEstimatedReclaimable: String { PurchasesL10n.string("purchases.premiumComponents.selectedEstimatedReclaimable") }
        /// Unlock unlimited scans, smart cleanup, and batch actions.
        public static var unlockUnlimitedScansSmartCleanup: String { PurchasesL10n.string("purchases.premiumComponents.unlockUnlimitedScansSmartCleanup") }
        /// Upgrade to Alike Pro
        public static var upgradeToAlikePro: String { PurchasesL10n.string("purchases.premiumComponents.upgradeToAlikePro") }
        /// View Alike Pro
        public static var viewAlikePro: String { PurchasesL10n.string("purchases.premiumComponents.viewAlikePro") }
        /// View plans
        public static var viewPlans: String { PurchasesL10n.string("purchases.premiumComponents.viewPlans") }
    }

    public enum SubscriptionPaywall {
        /// Advanced filters and batch cleanup
        public static var advancedFiltersAndBatchCleanup: String { PurchasesL10n.string("purchases.subscriptionPaywall.advancedFiltersAndBatchCleanup") }
        /// Alike Free still includes three scans each calendar month, review of existing results, and one-ph...
        public static var alikeFreeStillIncludesThree: String { PurchasesL10n.string("purchases.subscriptionPaywall.alikeFreeStillIncludesThree") }
        /// Alike Pro is now active.
        public static var alikeProIsNowActive: String { PurchasesL10n.string("purchases.subscriptionPaywall.alikeProIsNowActive") }
        /// Your Alike Pro subscription was restored.
        public static var alikeProSubscriptionWasRestored: String { PurchasesL10n.string("purchases.subscriptionPaywall.alikeProSubscriptionWasRestored") }
        /// Billed monthly
        public static var billedMonthly: String { PurchasesL10n.string("purchases.subscriptionPaywall.billedMonthly") }
        /// Billed yearly
        public static var billedYearly: String { PurchasesL10n.string("purchases.subscriptionPaywall.billedYearly") }
        /// You can continue using Alike Free while subscription plans are unavailable.
        public static var canContinueUsingAlikeFree: String { PurchasesL10n.string("purchases.subscriptionPaywall.canContinueUsingAlikeFree") }
        /// Check your connection and try loading subscription plans again.
        public static var checkConnectionTryLoadingSubscription: String { PurchasesL10n.string("purchases.subscriptionPaywall.checkConnectionTryLoadingSubscription") }
        /// A cleanup reminder on your schedule
        public static var cleanupReminderSchedule: String { PurchasesL10n.string("purchases.subscriptionPaywall.cleanupReminderSchedule") }
        /// Close
        public static var close: String { PurchasesL10n.string("purchases.subscriptionPaywall.close") }
        /// Continue with %@
        public static var continueWith: String { PurchasesL10n.string("purchases.subscriptionPaywall.continueWith") }
        /// Loading App Store plans…
        public static var loadingAppStorePlans: String { PurchasesL10n.string("purchases.subscriptionPaywall.loadingAppStorePlans") }
        /// No active Alike Pro subscription was found.
        public static var noActiveAlikeProSubscription: String { PurchasesL10n.string("purchases.subscriptionPaywall.noActiveAlikeProSubscription") }
        /// Pay for one month at a time
        public static var payOneMonthAtTime: String { PurchasesL10n.string("purchases.subscriptionPaywall.payOneMonthAtTime") }
        /// Plans aren't available yet
        public static var plansArentAvailableYet: String { PurchasesL10n.string("purchases.subscriptionPaywall.plansArentAvailableYet") }
        /// Plans couldn't be loaded
        public static var plansCouldntBeLoaded: String { PurchasesL10n.string("purchases.subscriptionPaywall.plansCouldntBeLoaded") }
        /// Privacy Policy
        public static var privacyPolicy: String { PurchasesL10n.string("purchases.subscriptionPaywall.privacyPolicy") }
        /// Your purchase is pending App Store approval.
        public static var purchasePendingAppStoreApproval: String { PurchasesL10n.string("purchases.subscriptionPaywall.purchasePendingAppStoreApproval") }
        /// Purchasing…
        public static var purchasing: String { PurchasesL10n.string("purchases.subscriptionPaywall.purchasing") }
        /// Recommended
        public static var recommended: String { PurchasesL10n.string("purchases.subscriptionPaywall.recommended") }
        /// Retry
        public static var retry: String { PurchasesL10n.string("purchases.subscriptionPaywall.retry") }
        /// Save %d%% compared with monthly
        public static var saveComparedWithMonthly: String { PurchasesL10n.string("purchases.subscriptionPaywall.saveComparedWithMonthly") }
        /// Save with annual billing
        public static var saveWithAnnualBilling: String { PurchasesL10n.string("purchases.subscriptionPaywall.saveWithAnnualBilling") }
        /// Select a subscription plan
        public static var selectASubscriptionPlan: String { PurchasesL10n.string("purchases.subscriptionPaywall.selectASubscriptionPlan") }
        /// Select this subscription plan
        public static var selectThisSubscriptionPlan: String { PurchasesL10n.string("purchases.subscriptionPaywall.selectThisSubscriptionPlan") }
        /// Smart screenshot and blurred-photo categories
        public static var smartScreenshotBlurredPhotoCategories: String { PurchasesL10n.string("purchases.subscriptionPaywall.smartScreenshotBlurredPhotoCategories") }
        /// Subscription plans unavailable
        public static var subscriptionPlansUnavailable: String { PurchasesL10n.string("purchases.subscriptionPaywall.subscriptionPlansUnavailable") }
        /// Subscriptions renew automatically unless cancelled at least 24 hours before the end of the curren...
        public static var subscriptionsRenewAutomaticallyUnlessCancelled: String { PurchasesL10n.string("purchases.subscriptionPaywall.subscriptionsRenewAutomaticallyUnlessCancelled") }
        /// Terms of Use
        public static var termsOfUse: String { PurchasesL10n.string("purchases.subscriptionPaywall.termsOfUse") }
        /// Unlimited library scans
        public static var unlimitedLibraryScans: String { PurchasesL10n.string("purchases.subscriptionPaywall.unlimitedLibraryScans") }
        /// Unlimited scans and all Pro cleanup tools are unlocked.
        public static var unlimitedScansAllProCleanup: String { PurchasesL10n.string("purchases.subscriptionPaywall.unlimitedScansAllProCleanup") }
        /// We couldn't complete your purchase. Check your connection and try again.
        public static var weCouldntCompletePurchaseCheck: String { PurchasesL10n.string("purchases.subscriptionPaywall.weCouldntCompletePurchaseCheck") }
        /// We couldn't restore your purchases. Check your connection and try again.
        public static var weCouldntRestorePurchasesCheck: String { PurchasesL10n.string("purchases.subscriptionPaywall.weCouldntRestorePurchasesCheck") }
        /// The yearly plan includes a 7-day free trial for eligible new subscribers. Billing starts when the...
        public static var yearlyPlanIncludes7Day: String { PurchasesL10n.string("purchases.subscriptionPaywall.yearlyPlanIncludes7Day") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }
}
