// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum DetailsL10n {
    public enum AlikeBestShotCelebration {
        /// Alike celebrating the Best Shot
        public static var alikeCelebratingTheBestShot: String { DetailsL10n.string("details.alikeBestShotCelebration.alikeCelebratingTheBestShot") }
    }

    public enum AlikeCleanupProgress {
        /// Estimated Savings
        public static var estimatedSavings: String { DetailsL10n.string("details.alikeCleanupProgress.estimatedSavings") }
        /// Organizing Photos
        public static var organizingPhotos: String { DetailsL10n.string("details.alikeCleanupProgress.organizingPhotos") }
        /// Selected Photos
        public static var selectedPhotos: String { DetailsL10n.string("details.alikeCleanupProgress.selectedPhotos") }
    }

    public enum AlikeComparisonReview {
        /// Alike comparing similar photos
        public static var alikeComparingSimilarPhotos: String { DetailsL10n.string("details.alikeComparisonReview.alikeComparingSimilarPhotos") }
    }

    public enum ClusterDetails {
        /// Move %1$lld Selected Photos to Recently Deleted? (plural)
        public static func deleteAlertTitle(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            DetailsL10n.plural("details.clusterDetails.deleteAlertTitle", count, bundle: bundle, locale: locale)
        }
        /// Cluster details are available on iOS.
        public static var clusterDetailsAvailableIOS: String { DetailsL10n.string("details.clusterDetails.clusterDetailsAvailableIOS") }
        /// Compare with the original
        public static var compareWithOriginal: String { DetailsL10n.string("details.clusterDetails.compareWithOriginal") }
        /// Switches between the original and the enhanced version
        public static var compareWithOriginalHint: String { DetailsL10n.string("details.clusterDetails.compareWithOriginalHint") }
        /// Created
        public static var created: String { DetailsL10n.string("details.clusterDetails.created") }
        /// Dates
        public static var dates: String { DetailsL10n.string("details.clusterDetails.dates") }
        /// Depth Effect
        public static var depthEffect: String { DetailsL10n.string("details.clusterDetails.depthEffect") }
        /// Details
        public static var details: String { DetailsL10n.string("details.clusterDetails.details") }
        /// Done
        public static var done: String { DetailsL10n.string("details.clusterDetails.done") }
        /// Double tap to remove this photo from cleanup selection
        public static var doubleTapRemoveThisPhoto: String { DetailsL10n.string("details.clusterDetails.doubleTapRemoveThisPhoto") }
        /// Double tap to reopen this cluster for review
        public static var doubleTapReopenThisCluster: String { DetailsL10n.string("details.clusterDetails.doubleTapReopenThisCluster") }
        /// Double tap to select this photo for cleanup
        public static var doubleTapSelectThisPhoto: String { DetailsL10n.string("details.clusterDetails.doubleTapSelectThisPhoto") }
        /// Apply
        public static var applyEnhancement: String { DetailsL10n.string("details.clusterDetails.applyEnhancement") }
        /// Enhance
        public static var enhance: String { DetailsL10n.string("details.clusterDetails.enhance") }
        /// Enhanced
        public static var enhanced: String { DetailsL10n.string("details.clusterDetails.enhanced") }
        /// Edited in another app
        public static var editedInAnotherAppNote: String { DetailsL10n.string("details.clusterDetails.editedInAnotherAppNote") }
        /// Applying replaces the edit made in another app. The original stays recoverable.
        public static var enhancementReplacesOtherEdit: String { DetailsL10n.string("details.clusterDetails.enhancementReplacesOtherEdit") }
        /// This photo was edited in another app, so Alike won't replace that edit.
        public static var enhancementEditedElsewhere: String { DetailsL10n.string("details.clusterDetails.enhancementEditedElsewhere") }
        /// Couldn't prepare the enhanced version of this photo.
        public static var enhancementRenderFailed: String { DetailsL10n.string("details.clusterDetails.enhancementRenderFailed") }
        /// Couldn't save the enhanced photo to your library.
        public static var enhancementSaveFailed: String { DetailsL10n.string("details.clusterDetails.enhancementSaveFailed") }
        /// Enhancement Unavailable
        public static var enhancementUnavailableTitle: String { DetailsL10n.string("details.clusterDetails.enhancementUnavailableTitle") }
        /// Alike can only enhance photos for now.
        public static var enhancementUnsupportedAsset: String { DetailsL10n.string("details.clusterDetails.enhancementUnsupportedAsset") }
        /// Photos shared through limited access can't be enhanced.
        public static var enhancementLimitedAccess: String { DetailsL10n.string("details.clusterDetails.enhancementLimitedAccess") }
        /// This photo was edited outside Alike, so Alike won't undo that edit.
        public static var enhancementNotOurs: String { DetailsL10n.string("details.clusterDetails.enhancementNotOurs") }
        /// The original photo isn't available right now.
        public static var enhancementOriginalUnavailable: String { DetailsL10n.string("details.clusterDetails.enhancementOriginalUnavailable") }
        /// Enhanced preview
        public static var enhancementPreviewTitle: String { DetailsL10n.string("details.clusterDetails.enhancementPreviewTitle") }
        /// Revert to original
        public static var revertToOriginal: String { DetailsL10n.string("details.clusterDetails.revertToOriginal") }
        /// Favorite
        public static var favorite: String { DetailsL10n.string("details.clusterDetails.favorite") }
        /// Finishes the review and keeps every photo in this cluster
        public static var finishesReviewKeepsEveryPhoto: String { DetailsL10n.string("details.clusterDetails.finishesReviewKeepsEveryPhoto") }
        /// Finishes the review and keeps the photos you did not select
        public static var finishesReviewKeepsPhotosDid: String { DetailsL10n.string("details.clusterDetails.finishesReviewKeepsPhotosDid") }
        /// HDR
        public static var hdr: String { DetailsL10n.string("details.clusterDetails.hdr") }
        /// Keeping %d of %d
        public static var keepingOf: String { DetailsL10n.string("details.clusterDetails.keepingOf") }
        /// No obvious Best Shot — choose one yourself
        public static var noObviousBestShot: String { DetailsL10n.string("details.clusterDetails.noObviousBestShot") }
        /// Original
        public static var originalPhoto: String { DetailsL10n.string("details.clusterDetails.originalPhoto") }
        /// Probably best
        public static var probablyBestShot: String { DetailsL10n.string("details.clusterDetails.probablyBestShot") }
        /// Better exposure
        public static var reasonBetterExposure: String { DetailsL10n.string("details.clusterDetails.reasonBetterExposure") }
        /// Face in focus
        public static var reasonFaceInFocus: String { DetailsL10n.string("details.clusterDetails.reasonFaceInFocus") }
        /// Higher resolution
        public static var reasonHigherResolution: String { DetailsL10n.string("details.clusterDetails.reasonHigherResolution") }
        /// Less noise
        public static var reasonLessNoise: String { DetailsL10n.string("details.clusterDetails.reasonLessNoise") }
        /// Eyes open
        public static var reasonOpenEyes: String { DetailsL10n.string("details.clusterDetails.reasonOpenEyes") }
        /// Sharper
        public static var reasonSharper: String { DetailsL10n.string("details.clusterDetails.reasonSharper") }
        /// Touch and hold to see the original
        public static var holdToCompare: String { DetailsL10n.string("details.clusterDetails.holdToCompare") }
        /// Live Photo
        public static var livePhoto: String { DetailsL10n.string("details.clusterDetails.livePhoto") }
        /// Location
        public static var location: String { DetailsL10n.string("details.clusterDetails.location") }
        /// Make Best Shot
        public static var makeBestShot: String { DetailsL10n.string("details.clusterDetails.makeBestShot") }
        /// Map showing where the photo was taken
        public static var mapShowingWherePhotoWas: String { DetailsL10n.string("details.clusterDetails.mapShowingWherePhotoWas") }
        /// Mark Reviewed
        public static var markReviewed: String { DetailsL10n.string("details.clusterDetails.markReviewed") }
        /// Megapixels
        public static var megapixels: String { DetailsL10n.string("details.clusterDetails.megapixels") }
        /// Modified
        public static var modified: String { DetailsL10n.string("details.clusterDetails.modified") }
        /// More Options
        public static var moreOptions: String { DetailsL10n.string("details.clusterDetails.moreOptions") }
        /// %@ MP
        public static var mp: String { DetailsL10n.string("details.clusterDetails.mp") }
        /// No
        public static var no: String { DetailsL10n.string("details.clusterDetails.no") }
        /// No Photos Available
        public static var noPhotosAvailable: String { DetailsL10n.string("details.clusterDetails.noPhotosAvailable") }
        /// Not selected
        public static var notSelected: String { DetailsL10n.string("details.clusterDetails.notSelected") }
        /// Open in Maps
        public static var openInMaps: String { DetailsL10n.string("details.clusterDetails.openInMaps") }
        /// Open Original
        public static var openOriginal: String { DetailsL10n.string("details.clusterDetails.openOriginal") }
        /// Opens the photo location in Maps
        public static var opensPhotoLocationMaps: String { DetailsL10n.string("details.clusterDetails.opensPhotoLocationMaps") }
        /// Panorama
        public static var panorama: String { DetailsL10n.string("details.clusterDetails.panorama") }
        /// Photo
        public static var photo: String { DetailsL10n.string("details.clusterDetails.photo") }
        /// Photo Info
        public static var photoInfo: String { DetailsL10n.string("details.clusterDetails.photoInfo") }
        /// Photo location
        public static var photoLocation: String { DetailsL10n.string("details.clusterDetails.photoLocation") }
        /// Resolution
        public static var resolution: String { DetailsL10n.string("details.clusterDetails.resolution") }
        /// Screenshot
        public static var screenshot: String { DetailsL10n.string("details.clusterDetails.screenshot") }
        /// Select All Except Best
        public static var selectAllExceptBest: String { DetailsL10n.string("details.clusterDetails.selectAllExceptBest") }
        /// Selected
        public static var selected: String { DetailsL10n.string("details.clusterDetails.selected") }
        /// Selected for cleanup review
        public static var selectedForCleanupReview: String { DetailsL10n.string("details.clusterDetails.selectedForCleanupReview") }
        /// The selected photo will be removed from your library and other devices using iCloud Photos, then ...
        public static var selectedPhotoWillBeRemoved: String { DetailsL10n.string("details.clusterDetails.selectedPhotoWillBeRemoved") }
        /// The selected photos will be removed from your library and other devices using iCloud Photos, then...
        public static var selectedPhotosWillBeRemoved: String { DetailsL10n.string("details.clusterDetails.selectedPhotosWillBeRemoved") }
        /// Selection
        public static var selection: String { DetailsL10n.string("details.clusterDetails.selection") }
        /// Selection shortcuts and grid layout
        public static var selectionShortcutsAndGridLayout: String { DetailsL10n.string("details.clusterDetails.selectionShortcutsAndGridLayout") }
        /// Show Info
        public static var showInfo: String { DetailsL10n.string("details.clusterDetails.showInfo") }
        /// Similar Photos
        public static var similarPhotos: String { DetailsL10n.string("details.clusterDetails.similarPhotos") }
        /// This photo is kept as the best shot. Long press another photo to make it the best shot instead.
        public static var thisPhotoKeptAsBest: String { DetailsL10n.string("details.clusterDetails.thisPhotoKeptAsBest") }
        /// Type
        public static var type: String { DetailsL10n.string("details.clusterDetails.type") }
        /// View
        public static var view: String { DetailsL10n.string("details.clusterDetails.view") }
        /// Yes
        public static var yes: String { DetailsL10n.string("details.clusterDetails.yes") }
    }

    public enum ClusterReviewActionBar {
        /// Move %1$lld Photos (plural)
        public static func moveSelectedPhotos(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            DetailsL10n.plural("details.clusterReviewActionBar.moveSelectedPhotos", count, bundle: bundle, locale: locale)
        }
        /// Moving...
        public static var moving: String { DetailsL10n.string("details.clusterReviewActionBar.moving") }
    }

    public enum ClusterReviewSummaryCard {
        /// %1$lld selected, estimated size %2$@. (plural)
        public static func selectionSummary(_ count: Int, _ estimatedSize: String, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            DetailsL10n.plural("details.clusterReviewSummaryCard.selectionSummary", count, estimatedSize, bundle: bundle, locale: locale)
        }
        /// Current cleanup review status
        public static var currentCleanupReviewStatus: String { DetailsL10n.string("details.clusterReviewSummaryCard.currentCleanupReviewStatus") }
        /// In review
        public static var inReview: String { DetailsL10n.string("details.clusterReviewSummaryCard.inReview") }
        /// Keeping %d of %d, estimated size %@.
        public static var keepingOfEstimatedSize: String { DetailsL10n.string("details.clusterReviewSummaryCard.keepingOfEstimatedSize") }
        /// 1 Similar Photo
        public static var n1SimilarPhoto: String { DetailsL10n.string("details.clusterReviewSummaryCard.n1SimilarPhoto") }
        /// Needs review
        public static var needsReview: String { DetailsL10n.string("details.clusterReviewSummaryCard.needsReview") }
        /// Not reviewed
        public static var notReviewed: String { DetailsL10n.string("details.clusterReviewSummaryCard.notReviewed") }
        /// %d Similar Photos
        public static var similarPhotos: String { DetailsL10n.string("details.clusterReviewSummaryCard.similarPhotos") }
        /// Tap photos to select them for cleanup
        public static var tapPhotosSelectThemCleanup: String { DetailsL10n.string("details.clusterReviewSummaryCard.tapPhotosSelectThemCleanup") }
    }

    public enum Common {
        /// Alike needs photo library access before it can delete photos. Open Settings to continue.
        public static var alikeNeedsPhotoLibraryAccess: String { DetailsL10n.string("details.common.alikeNeedsPhotoLibraryAccess") }
        /// Alike organizing selected photos
        public static var alikeOrganizingSelectedPhotos: String { DetailsL10n.string("details.common.alikeOrganizingSelectedPhotos") }
        /// Best Shot
        public static var bestShot: String { DetailsL10n.string("details.common.bestShot") }
        /// Cancel
        public static var cancel: String { DetailsL10n.string("details.common.cancel") }
        /// Cleanup Unavailable
        public static var cleanupUnavailable: String { DetailsL10n.string("details.common.cleanupUnavailable") }
        /// Clear Selection
        public static var clearSelection: String { DetailsL10n.string("details.common.clearSelection") }
        /// Close
        public static var close: String { DetailsL10n.string("details.common.close") }
        /// Couldn't move the selected photos. Please try again.
        public static var couldntMoveSelectedPhotosPlease: String { DetailsL10n.string("details.common.couldntMoveSelectedPhotosPlease") }
        /// Keeping all %d photos
        public static var keepingAllPhotos: String { DetailsL10n.string("details.common.keepingAllPhotos") }
        /// Loading photo preview
        public static var loadingPhotoPreview: String { DetailsL10n.string("details.common.loadingPhotoPreview") }
        /// Move
        public static var move: String { DetailsL10n.string("details.common.move") }
        /// Move the currently selected photos to Recently Deleted
        public static var moveCurrentlySelectedPhotosRecently: String { DetailsL10n.string("details.common.moveCurrentlySelectedPhotosRecently") }
        /// OK
        public static var ok: String { DetailsL10n.string("details.common.ok") }
        /// Open Settings
        public static var openSettings: String { DetailsL10n.string("details.common.openSettings") }
        /// Photo preview
        public static var photoPreview: String { DetailsL10n.string("details.common.photoPreview") }
        /// Photo preview unavailable
        public static var photoPreviewUnavailable: String { DetailsL10n.string("details.common.photoPreviewUnavailable") }
        /// Reviewed
        public static var reviewed: String { DetailsL10n.string("details.common.reviewed") }
        /// Select at least one photo before deleting.
        public static var selectAtLeastOnePhoto: String { DetailsL10n.string("details.common.selectAtLeastOnePhoto") }
        /// Some selected photos are no longer available. Your library access may be limited, or the library ...
        public static var someSelectedPhotosNoLonger: String { DetailsL10n.string("details.common.someSelectedPhotosNoLonger") }
    }

    public enum FullscreenZoomablePhoto {
        /// Retry
        public static var retry: String { DetailsL10n.string("details.fullscreenZoomablePhoto.retry") }
        /// Try loading the photo again
        public static var tryLoadingThePhotoAgain: String { DetailsL10n.string("details.fullscreenZoomablePhoto.tryLoadingThePhotoAgain") }
    }

    public enum ScreenshotCleanup {
        /// Screenshot cleanup is available on iOS.
        public static var screenshotCleanupAvailableIOS: String { DetailsL10n.string("details.screenshotCleanup.screenshotCleanupAvailableIOS") }
        /// Screenshots
        public static var screenshots: String { DetailsL10n.string("details.screenshotCleanup.screenshots") }
    }

    public enum ScreenshotCleanupComponents {
        /// Move Selected
        public static var moveSelected: String { DetailsL10n.string("details.screenshotCleanupComponents.moveSelected") }
        /// Moving...
        public static var moving: String { DetailsL10n.string("details.screenshotCleanupComponents.moving") }
        /// Choose which photos are selected for cleanup
        public static var chooseWhichPhotosSelectedCleanup: String { DetailsL10n.string("details.screenshotCleanupComponents.chooseWhichPhotosSelectedCleanup") }
        /// Select All
        public static var selectAll: String { DetailsL10n.string("details.screenshotCleanupComponents.selectAll") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }

    /// Resolves a key whose catalog entry carries plural variations. The count has to be the
    /// first argument and has to appear in every variation — `xcstringstool` rejects a plural
    /// variation that never references the number.
    static func plural(
        _ key: String,
        _ arguments: any CVarArg...,
        bundle: Bundle? = nil,
        locale: Locale? = nil
    ) -> String {
        let bundle = bundle ?? .module
        return String(
            format: bundle.localizedString(forKey: key, value: nil, table: nil),
            locale: locale ?? .alikeFormatting,
            arguments: arguments
        )
    }
}
