// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum CleanupL10n {
    public enum CleanupHistory {
        /// All-Time Impact
        public static var allTimeImpact: String { CleanupL10n.string("cleanup.cleanupHistory.allTimeImpact") }
        /// Cleanup Sessions
        public static var cleanupSessions: String { CleanupL10n.string("cleanup.cleanupHistory.cleanupSessions") }
        /// Completed cleanups will appear here.
        public static var completedCleanupsWillAppearHere: String { CleanupL10n.string("cleanup.cleanupHistory.completedCleanupsWillAppearHere") }
        /// Estimated Reclaimable
        public static var estimatedReclaimable: String { CleanupL10n.string("cleanup.cleanupHistory.estimatedReclaimable") }
        /// %2$@ estimated reclaimable, %1$lld photos moved to Recently Deleted (plural)
        public static func estimatedReclaimablePhotosMoved(
            _ count: Int,
            _ byteCount: String,
            bundle: Bundle? = nil,
            locale: Locale? = nil
        ) -> String {
            CleanupL10n.plural(
                "cleanup.cleanupHistory.estimatedReclaimablePhotosMoved",
                count, byteCount,
                bundle: bundle, locale: locale
            )
        }
        /// History
        public static var history: String { CleanupL10n.string("cleanup.cleanupHistory.history") }
        /// History Unavailable
        public static var historyUnavailable: String { CleanupL10n.string("cleanup.cleanupHistory.historyUnavailable") }
        /// Moved to Recently Deleted
        public static var movedToRecentlyDeleted: String { CleanupL10n.string("cleanup.cleanupHistory.movedToRecentlyDeleted") }
        /// No Cleanup History
        public static var noCleanupHistory: String { CleanupL10n.string("cleanup.cleanupHistory.noCleanupHistory") }
        /// Photos Moved to Recently Deleted
        public static var photosMovedToRecentlyDeleted: String { CleanupL10n.string("cleanup.cleanupHistory.photosMovedToRecentlyDeleted") }
        /// Recent Activity
        public static var recentActivity: String { CleanupL10n.string("cleanup.cleanupHistory.recentActivity") }
        /// Retry
        public static var retry: String { CleanupL10n.string("cleanup.cleanupHistory.retry") }
        /// Storage may not be freed until items are permanently deleted from Recently Deleted.
        public static var storageMayNotBeFreed: String { CleanupL10n.string("cleanup.cleanupHistory.storageMayNotBeFreed") }
        /// Unable to load cleanup history.
        public static var unableToLoadCleanupHistory: String { CleanupL10n.string("cleanup.cleanupHistory.unableToLoadCleanupHistory") }
    }

    public enum CleanupReminderManager {
        /// Open Alike this week to clear clutter and keep saving storage.
        public static var openAlikeThisWeekClear: String { CleanupL10n.string("cleanup.cleanupReminderManager.openAlikeThisWeekClear") }
        /// Ready for another cleanup?
        public static var readyForAnotherCleanup: String { CleanupL10n.string("cleanup.cleanupReminderManager.readyForAnotherCleanup") }
    }

    public enum Common {
        /// %1$lld photos (plural)
        public static func photos(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CleanupL10n.plural("cleanup.common.photos", count, bundle: bundle, locale: locale)
        }
    }

    public enum Main {
        /// All clusters
        public static var allClusters: String { CleanupL10n.string("cleanup.main.allClusters") }
        /// All clusters reviewed
        public static var allClustersReviewed: String { CleanupL10n.string("cleanup.main.allClustersReviewed") }
        /// All clusters reviewed. %d of %d clusters reviewed, %d selected, %@ estimated savings.
        public static var allClustersReviewedSelectedEstimated: String { CleanupL10n.string("cleanup.main.allClustersReviewedSelectedEstimated") }
        /// All review states
        public static var allReviewStates: String { CleanupL10n.string("cleanup.main.allReviewStates") }
        /// Any size
        public static var anySize: String { CleanupL10n.string("cleanup.main.anySize") }
        /// Changed
        public static var changed: String { CleanupL10n.string("cleanup.main.changed") }
        /// Cleanup
        public static var cleanup: String { CleanupL10n.string("cleanup.main.cleanup") }
        /// Cleanup History
        public static var cleanupHistory: String { CleanupL10n.string("cleanup.main.cleanupHistory") }
        /// Your cleanup results are up to date.
        public static var cleanupResultsUpDate: String { CleanupL10n.string("cleanup.main.cleanupResultsUpDate") }
        /// Cleanup Unavailable
        public static var cleanupUnavailable: String { CleanupL10n.string("cleanup.main.cleanupUnavailable") }
        /// Continue Review
        public static var continueReview: String { CleanupL10n.string("cleanup.main.continueReview") }
        /// Continue review. %d of %d clusters reviewed, %d remaining, %d selected, %@ estimated savings.
        public static var continueReviewClustersReviewedRemaining: String { CleanupL10n.string("cleanup.main.continueReviewClustersReviewedRemaining") }
        /// Couldn't Open Cleanup Category
        public static var couldntOpenCleanupCategory: String { CleanupL10n.string("cleanup.main.couldntOpenCleanupCategory") }
        /// Dismiss cleanup status
        public static var dismissCleanupStatus: String { CleanupL10n.string("cleanup.main.dismissCleanupStatus") }
        /// Done
        public static var done: String { CleanupL10n.string("cleanup.main.done") }
        /// Estimated Savings
        public static var estimatedSavings: String { CleanupL10n.string("cleanup.main.estimatedSavings") }
        /// Everything else still available in your cleanup queue
        public static var everythingElseStillAvailableCleanup: String { CleanupL10n.string("cleanup.main.everythingElseStillAvailableCleanup") }
        /// Favorites only
        public static var favoritesOnly: String { CleanupL10n.string("cleanup.main.favoritesOnly") }
        /// Filter and Sort
        public static var filterAndSort: String { CleanupL10n.string("cleanup.main.filterAndSort") }
        /// Filter and sort clusters
        public static var filterAndSortClusters: String { CleanupL10n.string("cleanup.main.filterAndSortClusters") }
        /// Filter by
        public static var filterBy: String { CleanupL10n.string("cleanup.main.filterBy") }
        /// Go to Scanner
        public static var goToScanner: String { CleanupL10n.string("cleanup.main.goToScanner") }
        /// Hide this status message
        public static var hideThisStatusMessage: String { CleanupL10n.string("cleanup.main.hideThisStatusMessage") }
        /// Highest similarity
        public static var highestSimilarity: String { CleanupL10n.string("cleanup.main.highestSimilarity") }
        /// In review
        public static var inReview: String { CleanupL10n.string("cleanup.main.inReview") }
        /// %1$lld items • %2$@ estimated reclaimable (plural)
        public static func itemsEstimatedReclaimable(
            _ count: Int,
            _ byteCount: String,
            bundle: Bundle? = nil,
            locale: Locale? = nil
        ) -> String {
            CleanupL10n.plural(
                "cleanup.main.itemsEstimatedReclaimable",
                count, byteCount,
                bundle: bundle, locale: locale
            )
        }
        /// Largest cluster
        public static var largestCluster: String { CleanupL10n.string("cleanup.main.largestCluster") }
        /// Your latest scan did not find similar photos or smart categories to review.
        public static var latestScanDidNotFind: String { CleanupL10n.string("cleanup.main.latestScanDidNotFind") }
        /// Locked
        public static var locked: String { CleanupL10n.string("cleanup.main.locked") }
        /// Minimum cluster size
        public static var minimumClusterSize: String { CleanupL10n.string("cleanup.main.minimumClusterSize") }
        /// Most space to save
        public static var mostSpaceToSave: String { CleanupL10n.string("cleanup.main.mostSpaceToSave") }
        /// Needs review
        public static var needsReview: String { CleanupL10n.string("cleanup.main.needsReview") }
        /// New
        public static var new: String { CleanupL10n.string("cleanup.main.new") }
        /// New and changed clusters after your latest rescan
        public static var newChangedClustersAfterLatest: String { CleanupL10n.string("cleanup.main.newChangedClustersAfterLatest") }
        /// Newest
        public static var newest: String { CleanupL10n.string("cleanup.main.newest") }
        /// No Cleanup Opportunities
        public static var noCleanupOpportunities: String { CleanupL10n.string("cleanup.main.noCleanupOpportunities") }
        /// No Clusters Match These Controls
        public static var noClustersMatchTheseControls: String { CleanupL10n.string("cleanup.main.noClustersMatchTheseControls") }
        /// Not reviewed
        public static var notReviewed: String { CleanupL10n.string("cleanup.main.notReviewed") }
        /// Nothing left to review right now
        public static var nothingLeftReviewRightNow: String { CleanupL10n.string("cleanup.main.nothingLeftReviewRightNow") }
        /// OK
        public static var ok: String { CleanupL10n.string("cleanup.main.ok") }
        /// Open next cluster to continue cleanup
        public static var openNextClusterContinueCleanup: String { CleanupL10n.string("cleanup.main.openNextClusterContinueCleanup") }
        /// Open this cleanup category
        public static var openThisCleanupCategory: String { CleanupL10n.string("cleanup.main.openThisCleanupCategory") }
        /// Open this cluster to review photos
        public static var openThisClusterReviewPhotos: String { CleanupL10n.string("cleanup.main.openThisClusterReviewPhotos") }
        /// Opens the upgrade options
        public static var opensTheUpgradeOptions: String { CleanupL10n.string("cleanup.main.opensTheUpgradeOptions") }
        /// %d or more photos
        public static var orMorePhotos: String { CleanupL10n.string("cleanup.main.orMorePhotos") }
        /// %1$lld photos moved to Recently Deleted. (plural)
        public static func photosMovedToRecentlyDeleted(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CleanupL10n.plural("cleanup.main.photosMovedToRecentlyDeleted", count, bundle: bundle, locale: locale)
        }
        /// The photos were deleted, but the library refresh failed. Run a new scan to refresh your results.
        public static var photosWereDeletedButLibrary: String { CleanupL10n.string("cleanup.main.photosWereDeletedButLibrary") }
        /// Pick up where you left off
        public static var pickUpWhereLeftOff: String { CleanupL10n.string("cleanup.main.pickUpWhereLeftOff") }
        /// Refresh Required
        public static var refreshRequired: String { CleanupL10n.string("cleanup.main.refreshRequired") }
        /// Refreshing Cleanup
        public static var refreshingCleanup: String { CleanupL10n.string("cleanup.main.refreshingCleanup") }
        /// Remaining
        public static var remaining: String { CleanupL10n.string("cleanup.main.remaining") }
        /// Rescan
        public static var rescan: String { CleanupL10n.string("cleanup.main.rescan") }
        /// Rescan Photos
        public static var rescanPhotos: String { CleanupL10n.string("cleanup.main.rescanPhotos") }
        /// Reset controls
        public static var resetControls: String { CleanupL10n.string("cleanup.main.resetControls") }
        /// Review status
        public static var reviewStatus: String { CleanupL10n.string("cleanup.main.reviewStatus") }
        /// Reviewed
        public static var reviewed: String { CleanupL10n.string("cleanup.main.reviewed") }
        /// Run a new scan to refresh cleanup suggestions.
        public static var runNewScanRefreshCleanup: String { CleanupL10n.string("cleanup.main.runNewScanRefreshCleanup") }
        /// Scan Failed
        public static var scanFailed: String { CleanupL10n.string("cleanup.main.scanFailed") }
        /// Scan Your Library First
        public static var scanYourLibraryFirst: String { CleanupL10n.string("cleanup.main.scanYourLibraryFirst") }
        /// Scanning your library… %d%%
        public static var scanningYourLibrary: String { CleanupL10n.string("cleanup.main.scanningYourLibrary") }
        /// Selected
        public static var selected: String { CleanupL10n.string("cleanup.main.selected") }
        /// Smart Cleanup
        public static var smartCleanup: String { CleanupL10n.string("cleanup.main.smartCleanup") }
        /// Sort by
        public static var sortBy: String { CleanupL10n.string("cleanup.main.sortBy") }
        /// Sort order
        public static var sortOrder: String { CleanupL10n.string("cleanup.main.sortOrder") }
        /// Start a scan to find similar photos and smart cleanup suggestions.
        public static var startScanFindSimilarPhotos: String { CleanupL10n.string("cleanup.main.startScanFindSimilarPhotos") }
        /// Try changing filters or resetting controls.
        public static var tryChangingFiltersResettingControls: String { CleanupL10n.string("cleanup.main.tryChangingFiltersResettingControls") }
        /// Unlock advanced filters
        public static var unlockAdvancedFilters: String { CleanupL10n.string("cleanup.main.unlockAdvancedFilters") }
        /// Your library changed
        public static var yourLibraryChanged: String { CleanupL10n.string("cleanup.main.yourLibraryChanged") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }

    /// Resolves a key whose catalog entry carries plural variations. The count has to be the
    /// first argument and has to appear in every variation — `xcstringstool` rejects a plural
    /// variation that never references the number.
    static func plural(
        _ key: String,
        _ arguments: any CVarArg...,
        bundle: Bundle? = nil,
        locale: Locale? = nil
    ) -> String {
        let bundle = bundle ?? .module
        return String(
            format: bundle.localizedString(forKey: key, value: nil, table: nil),
            locale: locale ?? .alikeFormatting,
            arguments: arguments
        )
    }
}
