// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum CoreL10n {
    public enum CleanupCategory {
        /// Move %1$lld Selected Blurred Photos to Recently Deleted? (plural)
        public static func alertTitleBlurredPhotos(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CoreL10n.plural("core.cleanupCategory.alertTitleBlurredPhotos", count, bundle: bundle, locale: locale)
        }
        /// Move %1$lld Selected Screenshots to Recently Deleted? (plural)
        public static func alertTitleScreenshots(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CoreL10n.plural("core.cleanupCategory.alertTitleScreenshots", count, bundle: bundle, locale: locale)
        }
        /// %1$lld selected, estimated size %2$@. (plural)
        public static func selectionSummary(_ count: Int, _ estimatedSize: String, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CoreL10n.plural("core.cleanupCategory.selectionSummary", count, estimatedSize, bundle: bundle, locale: locale)
        }
        /// %1$lld likely blurred photos available for review. (plural)
        public static func summaryBlurredPhotos(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CoreL10n.plural("core.cleanupCategory.summaryBlurredPhotos", count, bundle: bundle, locale: locale)
        }
        /// %1$lld screenshots available for review. (plural)
        public static func summaryScreenshots(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            CoreL10n.plural("core.cleanupCategory.summaryScreenshots", count, bundle: bundle, locale: locale)
        }
        /// Blurred Photo Cleanup
        public static var blurredPhotoCleanup: String { CoreL10n.string("core.cleanupCategory.blurredPhotoCleanup") }
        /// Blurred photo cleanup is a premium feature
        public static var blurredPhotoCleanupPremiumFeature: String { CoreL10n.string("core.cleanupCategory.blurredPhotoCleanupPremiumFeature") }
        /// Blurred Photos
        public static var blurredPhotos: String { CoreL10n.string("core.cleanupCategory.blurredPhotos") }
        /// Likely low-quality photos based on on-device analysis. Review before deleting.
        public static var likelyLowQualityPhotosBased: String { CoreL10n.string("core.cleanupCategory.likelyLowQualityPhotosBased") }
        /// No Blurred Photos Found
        public static var noBlurredPhotosFound: String { CoreL10n.string("core.cleanupCategory.noBlurredPhotosFound") }
        /// No Screenshots Found
        public static var noScreenshotsFound: String { CoreL10n.string("core.cleanupCategory.noScreenshotsFound") }
        /// Open blurred photo cleanup
        public static var openBlurredPhotoCleanup: String { CoreL10n.string("core.cleanupCategory.openBlurredPhotoCleanup") }
        /// Open screenshot cleanup
        public static var openScreenshotCleanup: String { CoreL10n.string("core.cleanupCategory.openScreenshotCleanup") }
        /// Opens the premium paywall for blurred photo cleanup
        public static var opensPremiumPaywallBlurredPhoto: String { CoreL10n.string("core.cleanupCategory.opensPremiumPaywallBlurredPhoto") }
        /// Opens the premium paywall for screenshot cleanup
        public static var opensPremiumPaywallScreenshotCleanup: String { CoreL10n.string("core.cleanupCategory.opensPremiumPaywallScreenshotCleanup") }
        /// Run a new scan after your library changes or if more photos need review.
        public static var runNewScanAfterLibrary: String { CoreL10n.string("core.cleanupCategory.runNewScanAfterLibrary") }
        /// Screenshot Cleanup
        public static var screenshotCleanup: String { CoreL10n.string("core.cleanupCategory.screenshotCleanup") }
        /// Screenshot cleanup is a premium feature
        public static var screenshotCleanupPremiumFeature: String { CoreL10n.string("core.cleanupCategory.screenshotCleanupPremiumFeature") }
        /// Screenshots
        public static var screenshots: String { CoreL10n.string("core.cleanupCategory.screenshots") }
        /// The selected photo will be removed from your library and other devices using iCloud Photos, then ...
        public static var selectedPhotoWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedPhotoWillBeRemoved") }
        /// The selected photos will be removed from your library and other devices using iCloud Photos, then...
        public static var selectedPhotosWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedPhotosWillBeRemoved") }
        /// The selected screenshot will be removed from your library and other devices using iCloud Photos, ...
        public static var selectedScreenshotWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedScreenshotWillBeRemoved") }
        /// The selected screenshots will be removed from your library and other devices using iCloud Photos,...
        public static var selectedScreenshotsWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedScreenshotsWillBeRemoved") }
        /// Try rescanning after your library updates.
        public static var tryRescanningAfterLibraryUpdates: String { CoreL10n.string("core.cleanupCategory.tryRescanningAfterLibraryUpdates") }
        /// Unlock blurred photo cleanup to review likely low-quality shots before deleting them with the sam...
        public static var unlockBlurredPhotoCleanupReview: String { CoreL10n.string("core.cleanupCategory.unlockBlurredPhotoCleanupReview") }
        /// Unlock screenshot cleanup to review and delete screenshots with the same safe confirmation flow.
        public static var unlockScreenshotCleanupReviewDelete: String { CoreL10n.string("core.cleanupCategory.unlockScreenshotCleanupReviewDelete") }
    }

    public enum SensitivityLevel {
        /// High
        public static var high: String { CoreL10n.string("core.sensitivityLevel.high") }
        /// Low
        public static var low: String { CoreL10n.string("core.sensitivityLevel.low") }
        /// Medium
        public static var medium: String { CoreL10n.string("core.sensitivityLevel.medium") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }

    /// Resolves a key whose catalog entry carries plural variations.
    ///
    /// The count has to be the first argument and has to appear in every variation:
    /// `xcstringstool` rejects a plural variation that never references the number.
    /// A compiled catalog stores these as a `.stringsdict` payload, so the lookup returns
    /// an `NSStringLocalizedFormatKey` format that `String(format:)` then resolves.
    static func plural(
        _ key: String,
        _ arguments: any CVarArg...,
        bundle: Bundle? = nil,
        locale: Locale? = nil
    ) -> String {
        let bundle = bundle ?? .module
        return String(
            format: bundle.localizedString(forKey: key, value: nil, table: nil),
            locale: locale ?? .current,
            arguments: arguments
        )
    }
}
