// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum CoreL10n {
    public enum CleanupCategory {
        /// Blurred Photo Cleanup
        public static var blurredPhotoCleanup: String { CoreL10n.string("core.cleanupCategory.blurredPhotoCleanup") }
        /// Blurred photo cleanup is a premium feature
        public static var blurredPhotoCleanupPremiumFeature: String { CoreL10n.string("core.cleanupCategory.blurredPhotoCleanupPremiumFeature") }
        /// Blurred Photos
        public static var blurredPhotos: String { CoreL10n.string("core.cleanupCategory.blurredPhotos") }
        /// %d likely blurred photos available for review.
        public static var likelyBlurredPhotosAvailableReview: String { CoreL10n.string("core.cleanupCategory.likelyBlurredPhotosAvailableReview") }
        /// Likely low-quality photos based on on-device analysis. Review before deleting.
        public static var likelyLowQualityPhotosBased: String { CoreL10n.string("core.cleanupCategory.likelyLowQualityPhotosBased") }
        /// Move 1 Selected Blurred Photo to Recently Deleted?
        public static var move1SelectedBlurredPhoto: String { CoreL10n.string("core.cleanupCategory.move1SelectedBlurredPhoto") }
        /// Move 1 Selected Screenshot to Recently Deleted?
        public static var move1SelectedScreenshotRecently: String { CoreL10n.string("core.cleanupCategory.move1SelectedScreenshotRecently") }
        /// Move %d Selected Blurred Photos to Recently Deleted?
        public static var moveSelectedBlurredPhotosRecently: String { CoreL10n.string("core.cleanupCategory.moveSelectedBlurredPhotosRecently") }
        /// Move %d Selected Screenshots to Recently Deleted?
        public static var moveSelectedScreenshotsRecentlyDeleted: String { CoreL10n.string("core.cleanupCategory.moveSelectedScreenshotsRecentlyDeleted") }
        /// 1 likely blurred photo available for review.
        public static var n1LikelyBlurredPhotoAvailable: String { CoreL10n.string("core.cleanupCategory.n1LikelyBlurredPhotoAvailable") }
        /// 1 screenshot available for review.
        public static var n1ScreenshotAvailableForReview: String { CoreL10n.string("core.cleanupCategory.n1ScreenshotAvailableForReview") }
        /// 1 selected, estimated size %@.
        public static var n1SelectedEstimatedSize: String { CoreL10n.string("core.cleanupCategory.n1SelectedEstimatedSize") }
        /// No Blurred Photos Found
        public static var noBlurredPhotosFound: String { CoreL10n.string("core.cleanupCategory.noBlurredPhotosFound") }
        /// No Screenshots Found
        public static var noScreenshotsFound: String { CoreL10n.string("core.cleanupCategory.noScreenshotsFound") }
        /// Open blurred photo cleanup
        public static var openBlurredPhotoCleanup: String { CoreL10n.string("core.cleanupCategory.openBlurredPhotoCleanup") }
        /// Open screenshot cleanup
        public static var openScreenshotCleanup: String { CoreL10n.string("core.cleanupCategory.openScreenshotCleanup") }
        /// Opens the premium paywall for blurred photo cleanup
        public static var opensPremiumPaywallBlurredPhoto: String { CoreL10n.string("core.cleanupCategory.opensPremiumPaywallBlurredPhoto") }
        /// Opens the premium paywall for screenshot cleanup
        public static var opensPremiumPaywallScreenshotCleanup: String { CoreL10n.string("core.cleanupCategory.opensPremiumPaywallScreenshotCleanup") }
        /// Run a new scan after your library changes or if more photos need review.
        public static var runNewScanAfterLibrary: String { CoreL10n.string("core.cleanupCategory.runNewScanAfterLibrary") }
        /// Screenshot Cleanup
        public static var screenshotCleanup: String { CoreL10n.string("core.cleanupCategory.screenshotCleanup") }
        /// Screenshot cleanup is a premium feature
        public static var screenshotCleanupPremiumFeature: String { CoreL10n.string("core.cleanupCategory.screenshotCleanupPremiumFeature") }
        /// Screenshots
        public static var screenshots: String { CoreL10n.string("core.cleanupCategory.screenshots") }
        /// %d screenshots available for review.
        public static var screenshotsAvailableForReview: String { CoreL10n.string("core.cleanupCategory.screenshotsAvailableForReview") }
        /// %d selected, estimated size %@.
        public static var selectedEstimatedSize: String { CoreL10n.string("core.cleanupCategory.selectedEstimatedSize") }
        /// The selected photo will be removed from your library and other devices using iCloud Photos, then ...
        public static var selectedPhotoWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedPhotoWillBeRemoved") }
        /// The selected photos will be removed from your library and other devices using iCloud Photos, then...
        public static var selectedPhotosWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedPhotosWillBeRemoved") }
        /// The selected screenshot will be removed from your library and other devices using iCloud Photos, ...
        public static var selectedScreenshotWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedScreenshotWillBeRemoved") }
        /// The selected screenshots will be removed from your library and other devices using iCloud Photos,...
        public static var selectedScreenshotsWillBeRemoved: String { CoreL10n.string("core.cleanupCategory.selectedScreenshotsWillBeRemoved") }
        /// Try rescanning after your library updates.
        public static var tryRescanningAfterLibraryUpdates: String { CoreL10n.string("core.cleanupCategory.tryRescanningAfterLibraryUpdates") }
        /// Unlock blurred photo cleanup to review likely low-quality shots before deleting them with the sam...
        public static var unlockBlurredPhotoCleanupReview: String { CoreL10n.string("core.cleanupCategory.unlockBlurredPhotoCleanupReview") }
        /// Unlock screenshot cleanup to review and delete screenshots with the same safe confirmation flow.
        public static var unlockScreenshotCleanupReviewDelete: String { CoreL10n.string("core.cleanupCategory.unlockScreenshotCleanupReviewDelete") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }
}
