// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum ScannerL10n {
    public enum Alike {
        /// Scan New Photos
        public static var librarychangedCta: String { ScannerL10n.string("scanner.alike.libraryChanged.cta") }
        /// New photos detected.
        public static var librarychangedMessage: String { ScannerL10n.string("scanner.alike.libraryChanged.message") }
        /// Scan again to refresh your cleanup opportunities.
        public static var librarychangedSupporting: String { ScannerL10n.string("scanner.alike.libraryChanged.supporting") }
        /// Start Scanning
        public static var readyCta: String { ScannerL10n.string("scanner.alike.ready.cta") }
        /// Ready when you are.
        public static var readyMessage: String { ScannerL10n.string("scanner.alike.ready.message") }
        /// Scan your photo library for cleanup opportunities.
        public static var readySupporting: String { ScannerL10n.string("scanner.alike.ready.supporting") }
    }

    public enum Main {
        /// How to Use
        public static var howToUse: String { ScannerL10n.string("scanner.main.howToUse") }
        /// Open usage instructions and cleanup workflow tips
        public static var openUsageInstructionsCleanupWorkflow: String { ScannerL10n.string("scanner.main.openUsageInstructionsCleanupWorkflow") }
        /// Scanner
        public static var scanner: String { ScannerL10n.string("scanner.main.scanner") }
    }

    public enum ScannerHome {
        /// You can switch tabs while scanning. Your cleanup results will refresh when it finishes.
        public static var canSwitchTabsWhileScanning: String { ScannerL10n.string("scanner.scannerHome.canSwitchTabsWhileScanning") }
        /// Cleanup opportunities are ready
        public static var cleanupOpportunitiesAreReady: String { ScannerL10n.string("scanner.scannerHome.cleanupOpportunitiesAreReady") }
        /// I couldn't finish this scan.
        public static var iCouldntFinishThisScan: String { ScannerL10n.string("scanner.scannerHome.iCouldntFinishThisScan") }
        /// Your library is up to date
        public static var libraryUpDate: String { ScannerL10n.string("scanner.scannerHome.libraryUpDate") }
        /// No cleanup opportunities were found in this scan.
        public static var noCleanupOpportunitiesWereFound: String { ScannerL10n.string("scanner.scannerHome.noCleanupOpportunitiesWereFound") }
        /// Retry
        public static var retry: String { ScannerL10n.string("scanner.scannerHome.retry") }
        /// Review Cleanup
        public static var reviewCleanup: String { ScannerL10n.string("scanner.scannerHome.reviewCleanup") }
        /// Review each suggestion before anything is removed.
        public static var reviewEachSuggestionBeforeAnything: String { ScannerL10n.string("scanner.scannerHome.reviewEachSuggestionBeforeAnything") }
        /// Review Existing Cleanup
        public static var reviewExistingCleanup: String { ScannerL10n.string("scanner.scannerHome.reviewExistingCleanup") }
        /// Scan Again
        public static var scanAgain: String { ScannerL10n.string("scanner.scannerHome.scanAgain") }
        /// Scanning your photo library
        public static var scanningYourPhotoLibrary: String { ScannerL10n.string("scanner.scannerHome.scanningYourPhotoLibrary") }
    }

    public enum ScannerHomeComponents {
        /// Blurred Photos
        public static var blurredPhotos: String { ScannerL10n.string("scanner.scannerHomeComponents.blurredPhotos") }
        /// Groups of photos that look alike.
        public static var groupsPhotosThatLookAlike: String { ScannerL10n.string("scanner.scannerHomeComponents.groupsPhotosThatLookAlike") }
        /// Last Scan
        public static var lastScan: String { ScannerL10n.string("scanner.scannerHomeComponents.lastScan") }
        /// Library Status
        public static var libraryStatus: String { ScannerL10n.string("scanner.scannerHomeComponents.libraryStatus") }
        /// Likely low-quality photos to review.
        public static var likelyLowQualityPhotosReview: String { ScannerL10n.string("scanner.scannerHomeComponents.likelyLowQualityPhotosReview") }
        /// Needs refresh
        public static var needsRefresh: String { ScannerL10n.string("scanner.scannerHomeComponents.needsRefresh") }
        /// %1$d of %2$d free scans remaining
        public static var ofFreeScansRemaining: String { ScannerL10n.string("scanner.scannerHomeComponents.ofFreeScansRemaining") }
        /// Opens the upgrade options
        public static var opensTheUpgradeOptions: String { ScannerL10n.string("scanner.scannerHomeComponents.opensTheUpgradeOptions") }
        /// Opportunities
        public static var opportunities: String { ScannerL10n.string("scanner.scannerHomeComponents.opportunities") }
        /// Reclaimable
        public static var reclaimable: String { ScannerL10n.string("scanner.scannerHomeComponents.reclaimable") }
        /// Scanning progress
        public static var scanningProgress: String { ScannerL10n.string("scanner.scannerHomeComponents.scanningProgress") }
        /// Screen captures that may no longer be useful.
        public static var screenCapturesThatMayNo: String { ScannerL10n.string("scanner.scannerHomeComponents.screenCapturesThatMayNo") }
        /// Screenshots
        public static var screenshots: String { ScannerL10n.string("scanner.scannerHomeComponents.screenshots") }
        /// Similar Photos
        public static var similarPhotos: String { ScannerL10n.string("scanner.scannerHomeComponents.similarPhotos") }
        /// These results are from before your photo library changed.
        public static var theseResultsFromBeforePhoto: String { ScannerL10n.string("scanner.scannerHomeComponents.theseResultsFromBeforePhoto") }
        /// Unlock more with Alike Pro
        public static var unlockMoreWithAlikePro: String { ScannerL10n.string("scanner.scannerHomeComponents.unlockMoreWithAlikePro") }
        /// Unlock unlimited scans, smart cleanup, and batch actions.
        public static var unlockUnlimitedScansSmartCleanup: String { ScannerL10n.string("scanner.scannerHomeComponents.unlockUnlimitedScansSmartCleanup") }
        /// What Alike checks
        public static var whatAlikeChecks: String { ScannerL10n.string("scanner.scannerHomeComponents.whatAlikeChecks") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }
}
