// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum DesignSystemL10n {
    public enum AlikeReaction {
        /// Alike celebrates your completed cleanup
        public static var alikeCelebratesYourCompletedCleanup: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeCelebratesYourCompletedCleanup") }
        /// Alike found cleanup opportunities
        public static var alikeFoundCleanupOpportunities: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeFoundCleanupOpportunities") }
        /// Alike has cleanup opportunities ready for review
        public static var alikeHasCleanupOpportunitiesReady: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeHasCleanupOpportunitiesReady") }
        /// Alike is ready for cleanup
        public static var alikeIsReadyForCleanup: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeIsReadyForCleanup") }
        /// Alike needs photo library permission to continue
        public static var alikeNeedsPhotoLibraryPermission: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeNeedsPhotoLibraryPermission") }
        /// Alike noticed new photos in your library
        public static var alikeNoticedNewPhotosLibrary: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeNoticedNewPhotosLibrary") }
        /// Alike ran into a problem with the scan
        public static var alikeRanIntoProblemWith: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeRanIntoProblemWith") }
        /// Alike is ready to help organize your photo library
        public static var alikeReadyHelpOrganizePhoto: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeReadyHelpOrganizePhoto") }
        /// Alike says your photo library is all caught up
        public static var alikeSaysPhotoLibraryAll: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeSaysPhotoLibraryAll") }
        /// Alike searching for similar photos
        public static var alikeSearchingForSimilarPhotos: String { DesignSystemL10n.string("designSystem.alikeReaction.alikeSearchingForSimilarPhotos") }
    }

    public enum PhotoGridColumnPreference {
        /// Choose how many columns are used to display photos
        public static var chooseHowManyColumnsUsed: String { DesignSystemL10n.string("designSystem.photoGridColumnPreference.chooseHowManyColumnsUsed") }
        /// %d Columns
        public static func columns(_ count: Int, bundle: Bundle? = nil, locale: Locale? = nil) -> String {
            DesignSystemL10n.plural("designSystem.photoGridColumnPreference.columns", count, bundle: bundle, locale: locale)
        }
        /// Columns
        public static var columns2: String { DesignSystemL10n.string("designSystem.photoGridColumnPreference.columns2") }
        /// Grid Columns
        public static var gridColumns: String { DesignSystemL10n.string("designSystem.photoGridColumnPreference.gridColumns") }
    }

    public enum PhotoLoadFailure {
        /// Photo preview unavailable
        public static var photoPreviewUnavailable: String { DesignSystemL10n.string("designSystem.photoLoadFailure.photoPreviewUnavailable") }
        /// Retry
        public static var retry: String { DesignSystemL10n.string("designSystem.photoLoadFailure.retry") }
        /// Try loading the photo again
        public static var tryLoadingThePhotoAgain: String { DesignSystemL10n.string("designSystem.photoLoadFailure.tryLoadingThePhotoAgain") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }

    /// Resolves a key whose catalog entry carries plural variations. The count has to be the
    /// first argument and has to appear in every variation — `xcstringstool` rejects a plural
    /// variation that never references the number.
    static func plural(
        _ key: String,
        _ arguments: any CVarArg...,
        bundle: Bundle? = nil,
        locale: Locale? = nil
    ) -> String {
        let bundle = bundle ?? .module
        return String(
            format: bundle.localizedString(forKey: key, value: nil, table: nil),
            locale: locale ?? .alikeFormatting,
            arguments: arguments
        )
    }
}
