import XCTest
@testable import Core

final class PersonalWeightModelTests: XCTestCase {
    private let global = PhotoQualityScoringConfig.current

    // MARK: - Floor

    func testFewerThanMinimumExamplesLeavesEachBranchUnchanged() {
        let examples = (0..<9).map { makeExample(hasFaces: true, sharpnessDelta: 0.3, index: $0) }
            + (0..<9).map { makeExample(hasFaces: false, sharpnessDelta: 0.3, index: $0) }

        let result = PersonalWeightModel.personalWeights(from: examples, global: global)

        XCTAssertEqual(result.withFaces, global.weightsWithFaces)
        XCTAssertEqual(result.withoutFaces, global.weightsWithoutFaces)
    }

    // MARK: - Determinism

    func testSameInputTwiceIsBitIdentical() {
        let examples = (0..<40).map { makeExample(hasFaces: true, sharpnessDelta: 0.2, index: $0) }

        let first = PersonalWeightModel.personalWeights(from: examples, global: global)
        let second = PersonalWeightModel.personalWeights(from: examples, global: global)

        XCTAssertEqual(first.withFaces, second.withFaces)
        XCTAssertEqual(first.withoutFaces, second.withoutFaces)
    }

    // MARK: - Branch isolation

    func testFacelessExamplesDoNotAffectTheFacedBranch() {
        let facelessOnly = (0..<50).map { makeExample(hasFaces: false, sharpnessDelta: 0.3, index: $0) }

        let result = PersonalWeightModel.personalWeights(from: facelessOnly, global: global)

        // No faced examples were supplied, so that branch stays at the floor.
        XCTAssertEqual(result.withFaces, global.weightsWithFaces)
    }

    func testFacedExamplesDoNotAffectTheFacelessBranch() {
        let facedOnly = (0..<50).map { makeExample(hasFaces: true, sharpnessDelta: 0.3, index: $0) }

        let result = PersonalWeightModel.personalWeights(from: facedOnly, global: global)

        XCTAssertEqual(result.withoutFaces, global.weightsWithoutFaces)
    }

    // MARK: - Movement grows with n

    func testMovementFromGlobalGrowsWithExampleCount() {
        // Small, consistent deltas: large ones saturate the +-0.15 box by
        // n=30 already, which would make d30 and d200 equal rather than
        // strictly increasing. The shrinkage curve itself is what this test
        // is verifying, so the per-example signal must stay well inside the
        // box across the whole range.
        let n10 = (0..<10).map { movementExample(index: $0) }
        let n30 = (0..<30).map { movementExample(index: $0) }
        let n200 = (0..<200).map { movementExample(index: $0) }

        let d10 = distance(
            PersonalWeightModel.personalWeights(from: n10, global: global).withFaces,
            global.weightsWithFaces
        )
        let d30 = distance(
            PersonalWeightModel.personalWeights(from: n30, global: global).withFaces,
            global.weightsWithFaces
        )
        let d200 = distance(
            PersonalWeightModel.personalWeights(from: n200, global: global).withFaces,
            global.weightsWithFaces
        )

        XCTAssertLessThan(d10, d30)
        XCTAssertLessThan(d30, d200)
    }

    /// Regression for the gradient-averaging fix: summing the per-example
    /// likelihood gradient instead of averaging it let the likelihood term
    /// outweigh the ridge by a factor of n, so on realistic-magnitude data
    /// beta shot to 5-25x the global vector and every branch saturated the
    /// +-0.15 box — the fit became "box corner in the mean-delta direction,"
    /// throwing away signal strength entirely. `testMovementFromGlobalGrowsWithExampleCount`
    /// above only ever varies n at one (tiny) magnitude, so it could not
    /// catch that: a fit that ignores magnitude still passes when the only
    /// axis under test is example count. This test varies magnitude at a
    /// fixed n instead, and checks the fit is nowhere near the box.
    ///
    /// Deltas are component-wise uniform in the range implied by the
    /// coordinator's own measurement of the ranker's cluster-normalised
    /// components (roughly +-0.4 as "realistic"), generated by a seeded
    /// linear congruential generator so the fixture is deterministic without
    /// hardcoding a literal array.
    func testSignalStrengthMovesTheFitRatherThanJustSaturatingTheBox() {
        let direction = lcgUnitValues(count: 200 * 5, seed: 0x5EED_1234)

        for n in [30, 200] {
            let weak = (0..<n).map { signalExample(index: $0, direction: direction, magnitude: 0.1) }
            let realistic = (0..<n).map { signalExample(index: $0, direction: direction, magnitude: 0.4) }
            let strong = (0..<n).map { signalExample(index: $0, direction: direction, magnitude: 0.8) }

            let weakResult = PersonalWeightModel.personalWeights(from: weak, global: global).withFaces
            let realisticResult = PersonalWeightModel.personalWeights(from: realistic, global: global).withFaces
            let strongResult = PersonalWeightModel.personalWeights(from: strong, global: global).withFaces

            // Not a corner of the box: the realistic-magnitude fit at
            // realistic volumes is exactly the case that used to saturate.
            assertNoComponentPinnedToBoxEdge(realisticResult, global: global.weightsWithFaces, n: n)

            // Same n, only the magnitude of the evidence differs: a fit that
            // is sensitive to signal strength must move further for the
            // stronger signal. This is the assertion the old sum-not-mean
            // gradient would fail, since every magnitude collapsed onto the
            // same box corner once n was large enough.
            let weakDistance = distance(weakResult, global.weightsWithFaces)
            let realisticDistance = distance(realisticResult, global.weightsWithFaces)
            let strongDistance = distance(strongResult, global.weightsWithFaces)
            XCTAssertLessThan(weakDistance, realisticDistance, "n=\(n)")
            XCTAssertLessThan(realisticDistance, strongDistance, "n=\(n)")
        }
    }

    // MARK: - Hard constraints, including adversarial input

    func testOutputAlwaysSumsToOneAndIsNonNegative() {
        for examples in adversarialExampleSets() {
            let result = PersonalWeightModel.personalWeights(from: examples, global: global)
            assertValidWeights(result.withFaces, file: #filePath, line: #line)
            assertValidWeights(result.withoutFaces, file: #filePath, line: #line)
        }
    }

    func testEveryComponentStaysWithinPointOneFiveOfGlobal() {
        for examples in adversarialExampleSets() {
            let result = PersonalWeightModel.personalWeights(from: examples, global: global)
            assertWithinBox(result.withFaces, of: global.weightsWithFaces)
            assertWithinBox(result.withoutFaces, of: global.weightsWithoutFaces)
        }
    }

    func testWithoutFacesFaceQualityIsExactlyZero() {
        for examples in adversarialExampleSets() {
            let result = PersonalWeightModel.personalWeights(from: examples, global: global)
            XCTAssertEqual(result.withoutFaces.faceQuality, 0)
        }
    }

    func testAllOnesDeltaLandsInsideTheBoxAndSumsToOne() {
        let examples = (0..<50).map { index -> BestShotOverrideExample in
            BestShotOverrideExample(
                recordedAt: Date(timeIntervalSince1970: Double(index)),
                clusterHasFaces: true,
                componentDelta: PhotoQualityScoringConfig.Weights(
                    sharpness: 1, faceQuality: 1, exposure: 1, noiseArtifacts: 1, resolution: 1
                ),
                offsetDelta: 0,
                scoringModelVersion: global.scoringModelVersion
            )
        }

        let result = PersonalWeightModel.personalWeights(from: examples, global: global)
        assertValidWeights(result.withFaces, file: #filePath, line: #line)
        assertWithinBox(result.withFaces, of: global.weightsWithFaces)
    }

    func testAllZeroDeltaLandsInsideTheBoxAndSumsToOne() {
        let examples = (0..<50).map { index -> BestShotOverrideExample in
            BestShotOverrideExample(
                recordedAt: Date(timeIntervalSince1970: Double(index)),
                clusterHasFaces: true,
                componentDelta: PhotoQualityScoringConfig.Weights(
                    sharpness: 0, faceQuality: 0, exposure: 0, noiseArtifacts: 0, resolution: 0
                ),
                offsetDelta: 0,
                scoringModelVersion: global.scoringModelVersion
            )
        }

        let result = PersonalWeightModel.personalWeights(from: examples, global: global)
        assertValidWeights(result.withFaces, file: #filePath, line: #line)
        assertWithinBox(result.withFaces, of: global.weightsWithFaces)
    }

    func testNonFiniteDeltaOrOffsetLandsInsideTheBoxAndSumsToOne() {
        var examples = (0..<50).map { makeExample(hasFaces: true, sharpnessDelta: 0.3, index: $0) }
        examples[3] = BestShotOverrideExample(
            recordedAt: Date(timeIntervalSince1970: 3),
            clusterHasFaces: true,
            componentDelta: PhotoQualityScoringConfig.Weights(
                sharpness: .infinity, faceQuality: 0, exposure: 0, noiseArtifacts: 0, resolution: 0
            ),
            offsetDelta: 0,
            scoringModelVersion: global.scoringModelVersion
        )
        examples[7] = BestShotOverrideExample(
            recordedAt: Date(timeIntervalSince1970: 7),
            clusterHasFaces: true,
            componentDelta: PhotoQualityScoringConfig.Weights(
                sharpness: 0, faceQuality: 0, exposure: 0, noiseArtifacts: 0, resolution: 0
            ),
            offsetDelta: .nan,
            scoringModelVersion: global.scoringModelVersion
        )

        let result = PersonalWeightModel.personalWeights(from: examples, global: global)
        assertValidWeights(result.withFaces, file: #filePath, line: #line)
        assertWithinBox(result.withFaces, of: global.weightsWithFaces)
    }

    func testAllExamplesNonFiniteFallsBackToGlobal() {
        let examples = (0..<50).map { index -> BestShotOverrideExample in
            BestShotOverrideExample(
                recordedAt: Date(timeIntervalSince1970: Double(index)),
                clusterHasFaces: true,
                componentDelta: PhotoQualityScoringConfig.Weights(
                    sharpness: .nan, faceQuality: 0, exposure: 0, noiseArtifacts: 0, resolution: 0
                ),
                offsetDelta: 0,
                scoringModelVersion: global.scoringModelVersion
            )
        }

        let result = PersonalWeightModel.personalWeights(from: examples, global: global)
        XCTAssertEqual(result.withFaces, global.weightsWithFaces)
    }

    // MARK: - The guardrail: weights only

    /// `personalWeights` returns a `(withFaces, withoutFaces)` pair of
    /// `Weights` — a five-component struct with no room for anything else.
    /// It physically cannot express a change to `absoluteSharpnessFloor`,
    /// the critical/strong/weak sharpness ratios or their penalties, the
    /// confidence thresholds, or any face-detection parameter. That matters:
    /// a blurred frame must never become Best Shot because of a few stray
    /// taps, and the only lever this model hands the user is how the five
    /// already-computed components are weighted against each other, never
    /// whether a frame clears the floor in the first place.
    func testReturnTypeCarriesWeightsOnlyNoThresholdsOrGates() {
        let examples = (0..<200).map { makeExample(hasFaces: true, sharpnessDelta: 0.3, index: $0) }

        let result = PersonalWeightModel.personalWeights(from: examples, global: global)

        // `Weights` has exactly these five stored properties (plus the
        // computed `total`); there is no field this assertion could miss
        // that would let a threshold or gate slip through the return type.
        _ = result.withFaces.sharpness
        _ = result.withFaces.faceQuality
        _ = result.withFaces.exposure
        _ = result.withFaces.noiseArtifacts
        _ = result.withFaces.resolution
        XCTAssertEqual(result.withFaces.total, 1, accuracy: 1e-9)

        // The un-personalised gates and floors are untouched by construction:
        // this call took no config beyond the global weights it started
        // from, and nothing it returns can be plugged back into
        // `absoluteSharpnessFloor` or any sharpness ratio.
        XCTAssertEqual(global.absoluteSharpnessFloor, PhotoQualityScoringConfig.current.absoluteSharpnessFloor)
    }

    // MARK: - Helpers

    /// A deterministic, seeded linear congruential generator, so a fixture
    /// spanning hundreds of examples does not have to be hand-typed while
    /// staying reproducible run to run (no `random`, no wall-clock seed).
    /// Values are in `[-1, 1]`; a caller scales by the desired magnitude.
    private func lcgUnitValues(count: Int, seed: UInt64) -> [Double] {
        var state = seed
        var values: [Double] = []
        values.reserveCapacity(count)
        for _ in 0..<count {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            let normalized = Double(state >> 11) / Double(1 << 53)
            values.append(normalized * 2 - 1)
        }
        return values
    }

    /// One override example whose `componentDelta` is the `index`-th slice
    /// of `direction`, scaled by `magnitude`. Reusing the same `direction`
    /// across magnitudes isolates signal *strength* as the only variable
    /// between a weak, realistic and strong fixture built from it.
    private func signalExample(
        index: Int,
        direction: [Double],
        magnitude: Double
    ) -> BestShotOverrideExample {
        let base = index * 5
        return BestShotOverrideExample(
            recordedAt: Date(timeIntervalSince1970: Double(index)),
            clusterHasFaces: true,
            componentDelta: PhotoQualityScoringConfig.Weights(
                sharpness: direction[base] * magnitude,
                faceQuality: direction[base + 1] * magnitude,
                exposure: direction[base + 2] * magnitude,
                noiseArtifacts: direction[base + 3] * magnitude,
                resolution: direction[base + 4] * magnitude
            ),
            offsetDelta: 0,
            scoringModelVersion: global.scoringModelVersion
        )
    }

    /// Asserts no component sits at (or past) its `+-0.15` box edge — the
    /// signature of a fit that saturated instead of tracking the evidence.
    private func assertNoComponentPinnedToBoxEdge(
        _ weights: PhotoQualityScoringConfig.Weights,
        global: PhotoQualityScoringConfig.Weights,
        n: Int,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        let margin = 0.01
        func assertNotPinned(_ value: Double, _ globalValue: Double, _ label: String) {
            XCTAssertLessThan(
                value, globalValue + 0.15 - margin,
                "\(label) pinned to the upper box edge at n=\(n)", file: file, line: line
            )
            // A component whose lower box edge falls below 0 is floored at
            // 0 by the >= 0 clamp before it could ever reach that edge, so
            // the lower-edge check only applies when the box itself allows
            // it — otherwise 0 is the floor, not evidence of saturation.
            if globalValue - 0.15 > 0 {
                XCTAssertGreaterThan(
                    value, globalValue - 0.15 + margin,
                    "\(label) pinned to the lower box edge at n=\(n)", file: file, line: line
                )
            }
        }
        assertNotPinned(weights.sharpness, global.sharpness, "sharpness")
        assertNotPinned(weights.faceQuality, global.faceQuality, "faceQuality")
        assertNotPinned(weights.exposure, global.exposure, "exposure")
        assertNotPinned(weights.noiseArtifacts, global.noiseArtifacts, "noiseArtifacts")
        assertNotPinned(weights.resolution, global.resolution, "resolution")
    }

    private func movementExample(index: Int) -> BestShotOverrideExample {
        BestShotOverrideExample(
            recordedAt: Date(timeIntervalSince1970: Double(index)),
            clusterHasFaces: true,
            componentDelta: PhotoQualityScoringConfig.Weights(
                sharpness: 0.005,
                faceQuality: 0.01,
                exposure: 0,
                noiseArtifacts: 0,
                resolution: 0
            ),
            offsetDelta: 0,
            scoringModelVersion: global.scoringModelVersion
        )
    }

    private func makeExample(
        hasFaces: Bool,
        sharpnessDelta: Double,
        index: Int
    ) -> BestShotOverrideExample {
        BestShotOverrideExample(
            recordedAt: Date(timeIntervalSince1970: Double(index)),
            clusterHasFaces: hasFaces,
            componentDelta: PhotoQualityScoringConfig.Weights(
                sharpness: sharpnessDelta,
                faceQuality: hasFaces ? 0.1 : 0,
                exposure: 0,
                noiseArtifacts: 0,
                resolution: 0
            ),
            offsetDelta: 0,
            scoringModelVersion: global.scoringModelVersion
        )
    }

    private func adversarialExampleSets() -> [[BestShotOverrideExample]] {
        let normal = (0..<50).map { makeExample(hasFaces: true, sharpnessDelta: 0.3, index: $0) }
        let allOnes = (0..<50).map { index -> BestShotOverrideExample in
            BestShotOverrideExample(
                recordedAt: Date(timeIntervalSince1970: Double(index)),
                clusterHasFaces: false,
                componentDelta: PhotoQualityScoringConfig.Weights(
                    sharpness: 1, faceQuality: 1, exposure: 1, noiseArtifacts: 1, resolution: 1
                ),
                offsetDelta: 0,
                scoringModelVersion: global.scoringModelVersion
            )
        }
        let allZeros = (0..<50).map { index -> BestShotOverrideExample in
            BestShotOverrideExample(
                recordedAt: Date(timeIntervalSince1970: Double(index)),
                clusterHasFaces: true,
                componentDelta: PhotoQualityScoringConfig.Weights(
                    sharpness: 0, faceQuality: 0, exposure: 0, noiseArtifacts: 0, resolution: 0
                ),
                offsetDelta: 0,
                scoringModelVersion: global.scoringModelVersion
            )
        }
        let withNonFinite = (0..<50).map { index -> BestShotOverrideExample in
            var sharpnessDelta: Double = 0.2
            if index == 5 { sharpnessDelta = .infinity }
            var exposureDelta: Double = 0
            if index == 12 { exposureDelta = .nan }
            var offset: Double = 0
            if index == 20 { offset = .infinity }
            let delta = PhotoQualityScoringConfig.Weights(
                sharpness: sharpnessDelta,
                faceQuality: 0,
                exposure: exposureDelta,
                noiseArtifacts: 0,
                resolution: 0
            )
            return BestShotOverrideExample(
                recordedAt: Date(timeIntervalSince1970: Double(index)),
                clusterHasFaces: false,
                componentDelta: delta,
                offsetDelta: offset,
                scoringModelVersion: global.scoringModelVersion
            )
        }
        let empty: [BestShotOverrideExample] = []
        return [normal, allOnes, allZeros, withNonFinite, empty]
    }

    private func assertValidWeights(
        _ weights: PhotoQualityScoringConfig.Weights,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        XCTAssertEqual(weights.total, 1, accuracy: 1e-9, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.sharpness, 0, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.faceQuality, 0, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.exposure, 0, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.noiseArtifacts, 0, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.resolution, 0, file: file, line: line)
    }

    private func assertWithinBox(
        _ weights: PhotoQualityScoringConfig.Weights,
        of global: PhotoQualityScoringConfig.Weights,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        let tolerance = 1e-9
        XCTAssertLessThanOrEqual(weights.sharpness, global.sharpness + 0.15 + tolerance, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.sharpness, global.sharpness - 0.15 - tolerance, file: file, line: line)
        XCTAssertLessThanOrEqual(weights.faceQuality, global.faceQuality + 0.15 + tolerance, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.faceQuality, global.faceQuality - 0.15 - tolerance, file: file, line: line)
        XCTAssertLessThanOrEqual(weights.exposure, global.exposure + 0.15 + tolerance, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.exposure, global.exposure - 0.15 - tolerance, file: file, line: line)
        XCTAssertLessThanOrEqual(weights.noiseArtifacts, global.noiseArtifacts + 0.15 + tolerance, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.noiseArtifacts, global.noiseArtifacts - 0.15 - tolerance, file: file, line: line)
        XCTAssertLessThanOrEqual(weights.resolution, global.resolution + 0.15 + tolerance, file: file, line: line)
        XCTAssertGreaterThanOrEqual(weights.resolution, global.resolution - 0.15 - tolerance, file: file, line: line)
    }

    private func distance(
        _ lhs: PhotoQualityScoringConfig.Weights,
        _ rhs: PhotoQualityScoringConfig.Weights
    ) -> Double {
        sqrt(
            pow(lhs.sharpness - rhs.sharpness, 2)
                + pow(lhs.faceQuality - rhs.faceQuality, 2)
                + pow(lhs.exposure - rhs.exposure, 2)
                + pow(lhs.noiseArtifacts - rhs.noiseArtifacts, 2)
                + pow(lhs.resolution - rhs.resolution, 2)
        )
    }
}
