// Generated by the task 39 localization split. Keys resolve against this
// package's own bundle — see Docs/Localization/README.md.

import Foundation

public enum UserGuideL10n {
    public enum A11y {
        /// Step %1$d of %2$d: %3$@
        public static var step: String { UserGuideL10n.string("userGuide.a11y.step") }
    }

    public enum CleanupQueue {
        /// Photos were added to or removed from a group you had already reviewed, so it's worth another look.
        public static var badgesChangedBody: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.changed.body") }
        /// Changed
        public static var badgesChangedTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.changed.title") }
        /// What the badges mean
        public static var badgesHeader: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.header") }
        /// You've selected photos here but haven't marked the group as reviewed.
        public static var badgesInReviewBody: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.inReview.body") }
        /// In review
        public static var badgesInReviewTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.inReview.title") }
        /// This group appeared in the most recent scan.
        public static var badgesNewBody: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.new.body") }
        /// New
        public static var badgesNewTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.new.title") }
        /// You haven't opened this group yet.
        public static var badgesNotReviewedBody: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.notReviewed.body") }
        /// Not reviewed
        public static var badgesNotReviewedTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.notReviewed.title") }
        /// You've made your decision about this group — whatever that decision was.
        public static var badgesReviewedBody: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.reviewed.body") }
        /// Reviewed
        public static var badgesReviewedTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.badges.reviewed.title") }
        /// Switch between a roomy one-column layout and a denser grid from the toolbar on any photo screen. ...
        public static var controlsColumnsBody: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.columns.body") }
        /// Columns
        public static var controlsColumnsTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.columns.title") }
        /// Narrow the list by review status, minimum group size, or favourites only. Sorting stays available...
        public static var controlsFiltersBody: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.filters.body") }
        /// Advanced filters
        public static var controlsFiltersTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.filters.title") }
        /// Reset controls puts sorting and filters back to their defaults.
        public static var controlsFooter: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.footer") }
        /// Sorting, filters and layout
        public static var controlsHeader: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.header") }
        /// Order groups by newest, most space to save, largest group, highest similarity, or review status.
        public static var controlsSortBody: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.sort.body") }
        /// Sort
        public static var controlsSortTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.controls.sort.title") }
        /// Opens the next group that still needs your attention, so you never have to hunt for where you sto...
        public static var progressContinueBody: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.continue.body") }
        /// Continue Review
        public static var progressContinueTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.continue.title") }
        /// Your progress
        public static var progressHeader: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.header") }
        /// Shows everything you've cleaned up so far, grouped by month, with your all-time total.
        public static var progressHistoryBody: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.history.body") }
        /// History
        public static var progressHistoryTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.history.title") }
        /// Estimated Savings is how much space your current selection would free once the photos are permane...
        public static var progressMetricsBody: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.metrics.body") }
        /// Reviewed, Remaining, Selected, Estimated Savings
        public static var progressMetricsTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.progress.metrics.title") }
        /// Every group Alike found, including the ones you already marked as reviewed.
        public static var sectionsAllBody: String { UserGuideL10n.string("userGuide.cleanupQueue.sections.all.body") }
        /// All clusters
        public static var sectionsAllTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.sections.all.title") }
        /// Needs review appears only when there is something new or changed to look at.
        public static var sectionsFooter: String { UserGuideL10n.string("userGuide.cleanupQueue.sections.footer") }
        /// Two lists of groups
        public static var sectionsHeader: String { UserGuideL10n.string("userGuide.cleanupQueue.sections.header") }
        /// Groups you haven't decided on yet, plus ones a rescan changed. Start here.
        public static var sectionsNeedsReviewBody: String { UserGuideL10n.string("userGuide.cleanupQueue.sections.needsReview.body") }
        /// Needs review
        public static var sectionsNeedsReviewTitle: String { UserGuideL10n.string("userGuide.cleanupQueue.sections.needsReview.title") }
        /// Your progress, the two cluster sections, badges, sorting and filters.
        public static var summary: String { UserGuideL10n.string("userGuide.cleanupQueue.summary") }
        /// Working through Cleanup
        public static var title: String { UserGuideL10n.string("userGuide.cleanupQueue.title") }
    }

    public enum ComparingPhotos {
        /// Favourites come first, then the highest resolution, then the most recent shot.
        public static var bestshotAutoBody: String { UserGuideL10n.string("userGuide.comparingPhotos.bestShot.auto.body") }
        /// How Alike picks it
        public static var bestshotAutoTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.bestShot.auto.title") }
        /// Your manual choice stays in place for as long as that photo exists.
        public static var bestshotFooter: String { UserGuideL10n.string("userGuide.comparingPhotos.bestShot.footer") }
        /// The Best Shot
        public static var bestshotHeader: String { UserGuideL10n.string("userGuide.comparingPhotos.bestShot.header") }
        /// Disagree? Press and hold any photo and choose Make Best Shot. The previous keeper joins your sele...
        public static var bestshotOverrideBody: String { UserGuideL10n.string("userGuide.comparingPhotos.bestShot.override.body") }
        /// Make Best Shot
        public static var bestshotOverrideTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.bestShot.override.title") }
        /// Opens the photo full screen. Swipe between the photos in the group and pinch to zoom in on the de...
        public static var inspectFullscreenBody: String { UserGuideL10n.string("userGuide.comparingPhotos.inspect.fullscreen.body") }
        /// Open Original
        public static var inspectFullscreenTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.inspect.fullscreen.title") }
        /// Looking closer
        public static var inspectHeader: String { UserGuideL10n.string("userGuide.comparingPhotos.inspect.header") }
        /// Press and hold a photo for resolution, file type, dates, favourite status, and where it was taken.
        public static var inspectInfoBody: String { UserGuideL10n.string("userGuide.comparingPhotos.inspect.info.body") }
        /// Show Info
        public static var inspectInfoTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.inspect.info.title") }
        /// What Alike learns stays on this device and is never uploaded.
        public static var personalizationFooter: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.footer") }
        /// Learning your taste
        public static var personalizationHeader: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.header") }
        /// Every time you choose a different Best Shot than the one Alike suggested, it remembers what you p...
        public static var personalizationLearnsBody: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.learns.body") }
        /// Alike learns from your picks
        public static var personalizationLearnsTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.learns.title") }
        /// This only changes how much sharpness, exposure, noise, and faces count against each other. A blur...
        public static var personalizationLimitsBody: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.limits.body") }
        /// What it won't do
        public static var personalizationLimitsTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.limits.title") }
        /// In Settings, Reset Best Shot Learning forgets everything Alike has picked up and returns to the d...
        public static var personalizationResetBody: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.reset.body") }
        /// Starting over
        public static var personalizationResetTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.personalization.reset.title") }
        /// Marking a group reviewed is your decision, not a consequence of selecting photos. You can reopen ...
        public static var reviewFooter: String { UserGuideL10n.string("userGuide.comparingPhotos.review.footer") }
        /// Finishing a group
        public static var reviewHeader: String { UserGuideL10n.string("userGuide.comparingPhotos.review.header") }
        /// If every photo in a group is worth keeping, mark it reviewed and move on. Nothing has to be removed.
        public static var reviewKeepAllBody: String { UserGuideL10n.string("userGuide.comparingPhotos.review.keepAll.body") }
        /// Keeping everything counts too
        public static var reviewKeepAllTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.review.keepAll.title") }
        /// The button at the bottom appears once something is selected, and always asks for confirmation first.
        public static var reviewMoveBody: String { UserGuideL10n.string("userGuide.comparingPhotos.review.move.body") }
        /// Move the selected photos
        public static var reviewMoveTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.review.move.title") }
        /// Use the seal button in the navigation bar when you're done with a group. Tap it again to reopen it.
        public static var reviewToggleBody: String { UserGuideL10n.string("userGuide.comparingPhotos.review.toggle.body") }
        /// Mark as reviewed
        public static var reviewToggleTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.review.toggle.title") }
        /// Alike Free moves one photo at a time. Alike Pro removes your whole selection in a single step.
        public static var selectionBatchBody: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.batch.body") }
        /// Removing several photos at once
        public static var selectionBatchTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.batch.title") }
        /// Your selection is saved, so closing a group and coming back later loses nothing.
        public static var selectionFooter: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.footer") }
        /// Choosing photos
        public static var selectionHeader: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.header") }
        /// In the ••• menu: select everything but the keeper in one go, or clear the whole selection.
        public static var selectionMenuBody: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.menu.body") }
        /// Select All Except Best
        public static var selectionMenuTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.menu.title") }
        /// Tap any photo to mark it for removal. Tap again to keep it. The Best Shot can't be selected.
        public static var selectionTapBody: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.tap.body") }
        /// Tap to select
        public static var selectionTapTitle: String { UserGuideL10n.string("userGuide.comparingPhotos.selection.tap.title") }
        /// Choosing what to keep inside a group, and marking it reviewed.
        public static var summary: String { UserGuideL10n.string("userGuide.comparingPhotos.summary") }
        /// Similar Photos and Best Shot
        public static var title: String { UserGuideL10n.string("userGuide.comparingPhotos.title") }
    }

    public enum DeletingSafely {
        /// Alike shows what will be moved and how much space it holds, then hands the request to the system.
        public static var flowConfirmBody: String { UserGuideL10n.string("userGuide.deletingSafely.flow.confirm.body") }
        /// iOS asks for confirmation
        public static var flowConfirmTitle: String { UserGuideL10n.string("userGuide.deletingSafely.flow.confirm.title") }
        /// Alike can't remove a photo on its own — iOS always asks you first.
        public static var flowFooter: String { UserGuideL10n.string("userGuide.deletingSafely.flow.footer") }
        /// Step by step
        public static var flowHeader: String { UserGuideL10n.string("userGuide.deletingSafely.flow.header") }
        /// If iCloud Photos is on, the same photos move to Recently Deleted on your other devices.
        public static var flowIcloudBody: String { UserGuideL10n.string("userGuide.deletingSafely.flow.icloud.body") }
        /// iCloud Photos syncs the change
        public static var flowIcloudTitle: String { UserGuideL10n.string("userGuide.deletingSafely.flow.icloud.title") }
        /// Photos land in the Photos app's Recently Deleted album, where you can restore any of them.
        public static var flowRecentlyDeletedBody: String { UserGuideL10n.string("userGuide.deletingSafely.flow.recentlyDeleted.body") }
        /// 30 days to change your mind
        public static var flowRecentlyDeletedTitle: String { UserGuideL10n.string("userGuide.deletingSafely.flow.recentlyDeleted.title") }
        /// Storage comes back only after the photos leave Recently Deleted — automatically after 30 days, or...
        public static var flowStorageBody: String { UserGuideL10n.string("userGuide.deletingSafely.flow.storage.body") }
        /// Space is freed at the end
        public static var flowStorageTitle: String { UserGuideL10n.string("userGuide.deletingSafely.flow.storage.title") }
        /// A timeline grouped by month, so you can see what you cleaned up and when.
        public static var historyActivityBody: String { UserGuideL10n.string("userGuide.deletingSafely.history.activity.body") }
        /// Recent Activity
        public static var historyActivityTitle: String { UserGuideL10n.string("userGuide.deletingSafely.history.activity.title") }
        /// Cleanup History
        public static var historyHeader: String { UserGuideL10n.string("userGuide.deletingSafely.history.header") }
        /// Your running totals: space reclaimed, photos moved, and cleanup sessions completed.
        public static var historyImpactBody: String { UserGuideL10n.string("userGuide.deletingSafely.history.impact.body") }
        /// All-Time Impact
        public static var historyImpactTitle: String { UserGuideL10n.string("userGuide.deletingSafely.history.impact.title") }
        /// Recently Deleted, when space is actually freed, and iCloud.
        public static var summary: String { UserGuideL10n.string("userGuide.deletingSafely.summary") }
        /// What happens when you delete
        public static var title: String { UserGuideL10n.string("userGuide.deletingSafely.title") }
    }

    public enum FreeAndPro {
        /// Results you've already scanned stay available, whether or not you subscribe.
        public static var freeFooter: String { UserGuideL10n.string("userGuide.freeAndPro.free.footer") }
        /// Included in Alike Free
        public static var freeHeader: String { UserGuideL10n.string("userGuide.freeAndPro.free.header") }
        /// Open every group, compare photos, change the Best Shot, and mark groups as reviewed.
        public static var freeReviewBody: String { UserGuideL10n.string("userGuide.freeAndPro.free.review.body") }
        /// Full review of similar photos
        public static var freeReviewTitle: String { UserGuideL10n.string("userGuide.freeAndPro.free.review.title") }
        /// Three scans each calendar month, with the counter resetting at the start of the next one.
        public static var freeScansBody: String { UserGuideL10n.string("userGuide.freeAndPro.free.scans.body") }
        /// Three scans a month
        public static var freeScansTitle: String { UserGuideL10n.string("userGuide.freeAndPro.free.scans.title") }
        /// You can move photos to Recently Deleted one by one.
        public static var freeSinglePhotoBody: String { UserGuideL10n.string("userGuide.freeAndPro.free.singlePhoto.body") }
        /// One photo at a time
        public static var freeSinglePhotoTitle: String { UserGuideL10n.string("userGuide.freeAndPro.free.singlePhoto.title") }
        /// Every sort order in Cleanup is available without a subscription.
        public static var freeSortingBody: String { UserGuideL10n.string("userGuide.freeAndPro.free.sorting.body") }
        /// All sorting options
        public static var freeSortingTitle: String { UserGuideL10n.string("userGuide.freeAndPro.free.sorting.title") }
        /// Move your entire selection in one step instead of one photo at a time.
        public static var proBatchBody: String { UserGuideL10n.string("userGuide.freeAndPro.pro.batch.body") }
        /// Batch cleanup
        public static var proBatchTitle: String { UserGuideL10n.string("userGuide.freeAndPro.pro.batch.title") }
        /// Open the Blurred Photos category and review what on-device analysis flagged.
        public static var proBlurredBody: String { UserGuideL10n.string("userGuide.freeAndPro.pro.blurred.body") }
        /// Blurred photos cleanup
        public static var proBlurredTitle: String { UserGuideL10n.string("userGuide.freeAndPro.pro.blurred.title") }
        /// Filter Cleanup by review status, minimum group size, or favourites only.
        public static var proFiltersBody: String { UserGuideL10n.string("userGuide.freeAndPro.pro.filters.body") }
        /// Advanced filters
        public static var proFiltersTitle: String { UserGuideL10n.string("userGuide.freeAndPro.pro.filters.title") }
        /// Manage or cancel a subscription any time in the App Store. Prices are shown before you subscribe.
        public static var proFooter: String { UserGuideL10n.string("userGuide.freeAndPro.pro.footer") }
        /// Added by Alike Pro
        public static var proHeader: String { UserGuideL10n.string("userGuide.freeAndPro.pro.header") }
        /// Choose the day and time of your weekly cleanup reminder.
        public static var proReminderBody: String { UserGuideL10n.string("userGuide.freeAndPro.pro.reminder.body") }
        /// Custom reminder schedule
        public static var proReminderTitle: String { UserGuideL10n.string("userGuide.freeAndPro.pro.reminder.title") }
        /// Open the Screenshots category and clear it in bulk.
        public static var proScreenshotsBody: String { UserGuideL10n.string("userGuide.freeAndPro.pro.screenshots.body") }
        /// Screenshots cleanup
        public static var proScreenshotsTitle: String { UserGuideL10n.string("userGuide.freeAndPro.pro.screenshots.title") }
        /// Rescan as often as you like, with no monthly allowance.
        public static var proUnlimitedScansBody: String { UserGuideL10n.string("userGuide.freeAndPro.pro.unlimitedScans.body") }
        /// Unlimited scans
        public static var proUnlimitedScansTitle: String { UserGuideL10n.string("userGuide.freeAndPro.pro.unlimitedScans.title") }
        /// What's included without a subscription, and what Pro adds.
        public static var summary: String { UserGuideL10n.string("userGuide.freeAndPro.summary") }
        /// Alike Free and Alike Pro
        public static var title: String { UserGuideL10n.string("userGuide.freeAndPro.title") }
    }

    public enum GettingStarted {
        /// Access and safety
        public static var accessHeader: String { UserGuideL10n.string("userGuide.gettingStarted.access.header") }
        /// Alike only ever suggests. Every removal needs your selection and the system confirmation.
        public static var accessNoAutoDeleteBody: String { UserGuideL10n.string("userGuide.gettingStarted.access.noAutoDelete.body") }
        /// Nothing is deleted automatically
        public static var accessNoAutoDeleteTitle: String { UserGuideL10n.string("userGuide.gettingStarted.access.noAutoDelete.title") }
        /// Photos are analysed on device. Nothing is uploaded anywhere.
        public static var accessOnDeviceBody: String { UserGuideL10n.string("userGuide.gettingStarted.access.onDevice.body") }
        /// Everything runs on your iPhone
        public static var accessOnDeviceTitle: String { UserGuideL10n.string("userGuide.gettingStarted.access.onDevice.title") }
        /// Alike needs read and write access to your library: read to analyse photos, write to move the ones...
        public static var accessPermissionBody: String { UserGuideL10n.string("userGuide.gettingStarted.access.permission.body") }
        /// Photo access
        public static var accessPermissionTitle: String { UserGuideL10n.string("userGuide.gettingStarted.access.permission.title") }
        /// You can stop after any step and pick up later — your progress is saved.
        public static var loopFooter: String { UserGuideL10n.string("userGuide.gettingStarted.loop.footer") }
        /// The three-step loop
        public static var loopHeader: String { UserGuideL10n.string("userGuide.gettingStarted.loop.header") }
        /// Confirm, and the selected photos go to Recently Deleted, where iOS keeps them for 30 days.
        public static var loopMoveBody: String { UserGuideL10n.string("userGuide.gettingStarted.loop.move.body") }
        /// Move to Recently Deleted
        public static var loopMoveTitle: String { UserGuideL10n.string("userGuide.gettingStarted.loop.move.title") }
        /// Open a group on the Cleanup tab, compare the photos, and choose which ones you no longer need.
        public static var loopReviewBody: String { UserGuideL10n.string("userGuide.gettingStarted.loop.review.body") }
        /// Review
        public static var loopReviewTitle: String { UserGuideL10n.string("userGuide.gettingStarted.loop.review.title") }
        /// Alike looks through your photo library on the Scanner tab and groups photos that look alike.
        public static var loopScanBody: String { UserGuideL10n.string("userGuide.gettingStarted.loop.scan.body") }
        /// Scan
        public static var loopScanTitle: String { UserGuideL10n.string("userGuide.gettingStarted.loop.scan.title") }
        /// Photos that look out of focus, gathered for you to check before removing.
        public static var scopeBlurredBody: String { UserGuideL10n.string("userGuide.gettingStarted.scope.blurred.body") }
        /// Blurred Photos
        public static var scopeBlurredTitle: String { UserGuideL10n.string("userGuide.gettingStarted.scope.blurred.title") }
        /// Alike analyses photos only. Videos are never read or included in a scan.
        public static var scopeFooter: String { UserGuideL10n.string("userGuide.gettingStarted.scope.footer") }
        /// What Alike looks at
        public static var scopeHeader: String { UserGuideL10n.string("userGuide.gettingStarted.scope.header") }
        /// Screen captures are kept out of similarity groups and collected in their own category.
        public static var scopeScreenshotsBody: String { UserGuideL10n.string("userGuide.gettingStarted.scope.screenshots.body") }
        /// Screenshots
        public static var scopeScreenshotsTitle: String { UserGuideL10n.string("userGuide.gettingStarted.scope.screenshots.title") }
        /// Bursts and near-duplicates that look alike — the same moment shot several times.
        public static var scopeSimilarBody: String { UserGuideL10n.string("userGuide.gettingStarted.scope.similar.body") }
        /// Similar Photos
        public static var scopeSimilarTitle: String { UserGuideL10n.string("userGuide.gettingStarted.scope.similar.title") }
        /// What Alike does, what it looks at, and the three-step loop.
        public static var summary: String { UserGuideL10n.string("userGuide.gettingStarted.summary") }
        /// Getting started
        public static var title: String { UserGuideL10n.string("userGuide.gettingStarted.title") }
    }

    public enum Hub {
        /// Alike never removes a photo without your confirmation.
        public static var footer: String { UserGuideL10n.string("userGuide.hub.footer") }
        /// Alike finds photos worth a second look, and lets you decide what stays.
        public static var intro: String { UserGuideL10n.string("userGuide.hub.intro") }
        /// No Results
        public static var noresults: String { UserGuideL10n.string("userGuide.hub.noResults") }
        /// Try a different word, or browse the topics.
        public static var noresultsMessage: String { UserGuideL10n.string("userGuide.hub.noResults.message") }
        /// Search the guide
        public static var searchprompt: String { UserGuideL10n.string("userGuide.hub.searchPrompt") }
        /// Opens this guide topic
        public static var topicHint: String { UserGuideL10n.string("userGuide.hub.topic.hint") }
        /// Topics
        public static var topicsHeader: String { UserGuideL10n.string("userGuide.hub.topics.header") }
    }

    public enum Privacy {
        /// Find it in Settings, under Data & Privacy. It can't be undone.
        public static var deletedataFooter: String { UserGuideL10n.string("userGuide.privacy.deleteData.footer") }
        /// Delete Alike Data
        public static var deletedataHeader: String { UserGuideL10n.string("userGuide.privacy.deleteData.header") }
        /// Your photos, your Recently Deleted album, your photo access, and your Alike Pro subscription.
        public static var deletedataKeptBody: String { UserGuideL10n.string("userGuide.privacy.deleteData.kept.body") }
        /// What stays untouched
        public static var deletedataKeptTitle: String { UserGuideL10n.string("userGuide.privacy.deleteData.kept.title") }
        /// Scan results and analysis caches, cleanup progress and history, and your Alike preferences.
        public static var deletedataRemovedBody: String { UserGuideL10n.string("userGuide.privacy.deleteData.removed.body") }
        /// What gets erased
        public static var deletedataRemovedTitle: String { UserGuideL10n.string("userGuide.privacy.deleteData.removed.title") }
        /// Alike shows its introduction again afterwards, without asking for photo access a second time.
        public static var deletedataReplayBody: String { UserGuideL10n.string("userGuide.privacy.deleteData.replay.body") }
        /// Starting fresh
        public static var deletedataReplayTitle: String { UserGuideL10n.string("userGuide.privacy.deleteData.replay.title") }
        /// Photos are compared using Apple's on-device vision framework, and the results are stored locally.
        public static var ondeviceAnalysisBody: String { UserGuideL10n.string("userGuide.privacy.onDevice.analysis.body") }
        /// Analysis never leaves your iPhone
        public static var ondeviceAnalysisTitle: String { UserGuideL10n.string("userGuide.privacy.onDevice.analysis.title") }
        /// Alike has no account, no sign-in, and no server of its own.
        public static var ondeviceFooter: String { UserGuideL10n.string("userGuide.privacy.onDevice.footer") }
        /// On your device
        public static var ondeviceHeader: String { UserGuideL10n.string("userGuide.privacy.onDevice.header") }
        /// The only network requests Alike makes are to the App Store, for subscriptions.
        public static var ondeviceNetworkBody: String { UserGuideL10n.string("userGuide.privacy.onDevice.network.body") }
        /// Your photos are never uploaded
        public static var ondeviceNetworkTitle: String { UserGuideL10n.string("userGuide.privacy.onDevice.network.title") }
        /// What Alike asks for
        public static var permissionsHeader: String { UserGuideL10n.string("userGuide.privacy.permissions.header") }
        /// Requested only if you turn on the weekly cleanup reminder, and never otherwise.
        public static var permissionsNotificationsBody: String { UserGuideL10n.string("userGuide.privacy.permissions.notifications.body") }
        /// Notifications
        public static var permissionsNotificationsTitle: String { UserGuideL10n.string("userGuide.privacy.permissions.notifications.title") }
        /// Requested once at the start. You can change or limit it any time in iOS Settings.
        public static var permissionsPhotosBody: String { UserGuideL10n.string("userGuide.privacy.permissions.photos.body") }
        /// Photo library
        public static var permissionsPhotosTitle: String { UserGuideL10n.string("userGuide.privacy.permissions.photos.title") }
        /// What stays on your device, what Alike asks for, and how to erase its data.
        public static var summary: String { UserGuideL10n.string("userGuide.privacy.summary") }
        /// Privacy and your data
        public static var title: String { UserGuideL10n.string("userGuide.privacy.title") }
    }

    public enum Scanning {
        /// The card explains what went wrong and offers Retry. Earlier results stay available in the meantime.
        public static var rescanErrorBody: String { UserGuideL10n.string("userGuide.scanning.rescan.error.body") }
        /// A scan didn't finish
        public static var rescanErrorTitle: String { UserGuideL10n.string("userGuide.scanning.rescan.error.title") }
        /// A refresh that runs by itself after you move photos does not count against your free scans.
        public static var rescanFooter: String { UserGuideL10n.string("userGuide.scanning.rescan.footer") }
        /// When to scan again
        public static var rescanHeader: String { UserGuideL10n.string("userGuide.scanning.rescan.header") }
        /// When you add or remove photos elsewhere, Alike marks the results as needing a refresh and offers ...
        public static var rescanLibraryChangedBody: String { UserGuideL10n.string("userGuide.scanning.rescan.libraryChanged.body") }
        /// Your library changed
        public static var rescanLibraryChangedTitle: String { UserGuideL10n.string("userGuide.scanning.rescan.libraryChanged.title") }
        /// Sensitivity decides how alike two photos must be to land in the same group, so Alike asks to resc...
        public static var rescanSensitivityBody: String { UserGuideL10n.string("userGuide.scanning.rescan.sensitivity.body") }
        /// You changed sensitivity
        public static var rescanSensitivityTitle: String { UserGuideL10n.string("userGuide.scanning.rescan.sensitivity.title") }
        /// Scanning continues when you switch tabs. Cleanup refreshes on its own once it finishes.
        public static var runBackgroundBody: String { UserGuideL10n.string("userGuide.scanning.run.background.body") }
        /// Keep using the app while it works
        public static var runBackgroundTitle: String { UserGuideL10n.string("userGuide.scanning.run.background.title") }
        /// Alike remembers what it learned about each photo and only re-analyses what actually changed.
        public static var runCacheBody: String { UserGuideL10n.string("userGuide.scanning.run.cache.body") }
        /// Later scans are faster
        public static var runCacheTitle: String { UserGuideL10n.string("userGuide.scanning.run.cache.title") }
        /// The Scanner card changes as the scan progresses and tells you what to do next.
        public static var runFooter: String { UserGuideL10n.string("userGuide.scanning.run.footer") }
        /// Running a scan
        public static var runHeader: String { UserGuideL10n.string("userGuide.scanning.run.header") }
        /// Tap the button on the Scanner tab. A progress bar shows how far along the analysis is.
        public static var runStartBody: String { UserGuideL10n.string("userGuide.scanning.run.start.body") }
        /// Start scanning
        public static var runStartTitle: String { UserGuideL10n.string("userGuide.scanning.run.start.title") }
        /// Alike Free includes three scans each calendar month. The counter resets at the start of the next ...
        public static var statusAllowanceBody: String { UserGuideL10n.string("userGuide.scanning.status.allowance.body") }
        /// Free scans remaining
        public static var statusAllowanceTitle: String { UserGuideL10n.string("userGuide.scanning.status.allowance.title") }
        /// After your first scan the card shows when it ran, how many opportunities were found, and how much...
        public static var statusCardBody: String { UserGuideL10n.string("userGuide.scanning.status.card.body") }
        /// Last scan at a glance
        public static var statusCardTitle: String { UserGuideL10n.string("userGuide.scanning.status.card.title") }
        /// Library status
        public static var statusHeader: String { UserGuideL10n.string("userGuide.scanning.status.header") }
        /// Running a scan, reading the Scanner card, and knowing when to rescan.
        public static var summary: String { UserGuideL10n.string("userGuide.scanning.summary") }
        /// Scanning your library
        public static var title: String { UserGuideL10n.string("userGuide.scanning.title") }
    }

    public enum SettingsAndReminders {
        /// Changing sensitivity asks for a rescan, because the groups have to be built again.
        public static var analysisFooter: String { UserGuideL10n.string("userGuide.settingsAndReminders.analysis.footer") }
        /// Tuning the results
        public static var analysisHeader: String { UserGuideL10n.string("userGuide.settingsAndReminders.analysis.header") }
        /// Alike is available in English and Ukrainian. The switch opens the iOS Settings page for the app.
        public static var analysisLanguageBody: String { UserGuideL10n.string("userGuide.settingsAndReminders.analysis.language.body") }
        /// Change Language
        public static var analysisLanguageTitle: String { UserGuideL10n.string("userGuide.settingsAndReminders.analysis.language.title") }
        /// Low groups only near-identical photos. High casts a wider net and finds more, but loosely related...
        public static var analysisSensitivityBody: String { UserGuideL10n.string("userGuide.settingsAndReminders.analysis.sensitivity.body") }
        /// Sensitivity
        public static var analysisSensitivityTitle: String { UserGuideL10n.string("userGuide.settingsAndReminders.analysis.sensitivity.title") }
        /// The reminder is off until you turn it on, and asks for notification permission the first time.
        public static var reminderFooter: String { UserGuideL10n.string("userGuide.settingsAndReminders.reminder.footer") }
        /// Weekly cleanup reminder
        public static var reminderHeader: String { UserGuideL10n.string("userGuide.settingsAndReminders.reminder.header") }
        /// Alike Pro lets you move the reminder to whichever day and time suits you.
        public static var reminderScheduleBody: String { UserGuideL10n.string("userGuide.settingsAndReminders.reminder.schedule.body") }
        /// Pick your own day and time
        public static var reminderScheduleTitle: String { UserGuideL10n.string("userGuide.settingsAndReminders.reminder.schedule.title") }
        /// A gentle reminder to spend a few minutes on cleanup. On Alike Free it arrives on Sunday evening.
        public static var reminderWeeklyBody: String { UserGuideL10n.string("userGuide.settingsAndReminders.reminder.weekly.body") }
        /// A nudge once a week
        public static var reminderWeeklyTitle: String { UserGuideL10n.string("userGuide.settingsAndReminders.reminder.weekly.title") }
        /// Your subscription
        public static var subscriptionHeader: String { UserGuideL10n.string("userGuide.settingsAndReminders.subscription.header") }
        /// On a new device, or after reinstalling, this brings your existing subscription back.
        public static var subscriptionRestoreBody: String { UserGuideL10n.string("userGuide.settingsAndReminders.subscription.restore.body") }
        /// Restore Purchases
        public static var subscriptionRestoreTitle: String { UserGuideL10n.string("userGuide.settingsAndReminders.subscription.restore.title") }
        /// The card at the top of Settings shows whether Alike Pro is active and when it renews.
        public static var subscriptionStatusBody: String { UserGuideL10n.string("userGuide.settingsAndReminders.subscription.status.body") }
        /// Subscription status
        public static var subscriptionStatusTitle: String { UserGuideL10n.string("userGuide.settingsAndReminders.subscription.status.title") }
        /// Sensitivity, language, the weekly reminder and your subscription.
        public static var summary: String { UserGuideL10n.string("userGuide.settingsAndReminders.summary") }
        /// Settings and reminders
        public static var title: String { UserGuideL10n.string("userGuide.settingsAndReminders.title") }
    }

    public enum SmartCategories {
        /// Alike suggests only the softest few percent of your photos, and only when there are enough to com...
        public static var blurdetectionConservativeBody: String { UserGuideL10n.string("userGuide.smartCategories.blurDetection.conservative.body") }
        /// Only the clearest cases
        public static var blurdetectionConservativeTitle: String { UserGuideL10n.string("userGuide.smartCategories.blurDetection.conservative.title") }
        /// Photos you marked as favourites never appear here — mark a photo as a favourite to protect it.
        public static var blurdetectionFavoritesBody: String { UserGuideL10n.string("userGuide.smartCategories.blurDetection.favorites.body") }
        /// Favourites are left alone
        public static var blurdetectionFavoritesTitle: String { UserGuideL10n.string("userGuide.smartCategories.blurDetection.favorites.title") }
        /// A short list is intentional: a missed blurry photo costs you nothing, a wrongly flagged keepsake ...
        public static var blurdetectionFooter: String { UserGuideL10n.string("userGuide.smartCategories.blurDetection.footer") }
        /// Why the blurred list is short
        public static var blurdetectionHeader: String { UserGuideL10n.string("userGuide.smartCategories.blurDetection.header") }
        /// Photos that look out of focus, based on on-device analysis. Worth checking before you remove them.
        public static var categoriesBlurredBody: String { UserGuideL10n.string("userGuide.smartCategories.categories.blurred.body") }
        /// Blurred Photos
        public static var categoriesBlurredTitle: String { UserGuideL10n.string("userGuide.smartCategories.categories.blurred.title") }
        /// Both categories are part of Alike Pro. Tapping a locked one shows what it found first.
        public static var categoriesFooter: String { UserGuideL10n.string("userGuide.smartCategories.categories.footer") }
        /// Two extra categories
        public static var categoriesHeader: String { UserGuideL10n.string("userGuide.smartCategories.categories.header") }
        /// Screen captures collected in one place, with the space they take up.
        public static var categoriesScreenshotsBody: String { UserGuideL10n.string("userGuide.smartCategories.categories.screenshots.body") }
        /// Screenshots
        public static var categoriesScreenshotsTitle: String { UserGuideL10n.string("userGuide.smartCategories.categories.screenshots.title") }
        /// Screenshots and Blurred Photos, gathered outside the similarity groups.
        public static var summary: String { UserGuideL10n.string("userGuide.smartCategories.summary") }
        /// Smart Cleanup
        public static var title: String { UserGuideL10n.string("userGuide.smartCategories.title") }
        /// How they work
        public static var workflowHeader: String { UserGuideL10n.string("userGuide.smartCategories.workflow.header") }
        /// Press and hold for Show Info or Open Original, and adjust columns from the toolbar.
        public static var workflowInspectBody: String { UserGuideL10n.string("userGuide.smartCategories.workflow.inspect.body") }
        /// Same tools as a group
        public static var workflowInspectTitle: String { UserGuideL10n.string("userGuide.smartCategories.workflow.inspect.title") }
        /// One button selects everything or clears the selection, and the summary keeps a running total.
        public static var workflowSelectBody: String { UserGuideL10n.string("userGuide.smartCategories.workflow.select.body") }
        /// Select All or pick individually
        public static var workflowSelectTitle: String { UserGuideL10n.string("userGuide.smartCategories.workflow.select.title") }
    }

    public enum UserGuideHub {
        /// How to Use
        public static var howToUse: String { UserGuideL10n.string("userGuide.userGuideHub.howToUse") }
    }

    public enum UserGuideSheet {
        /// Close
        public static var close: String { UserGuideL10n.string("userGuide.userGuideSheet.close") }
    }

    /// Resolves a key that is chosen at runtime against this package's catalog.
    public static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }
}
